### ISSUE TITLE
Cleanup `get_rendered_html_form` and `get_raw_data_form`

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2089]
The `BrowsableAPIRenderer` does some pretty ugly hackery in creating the raw data form and HTML input form. We really need to spend some time rationalizing this and cleaning it up.

**Comment by tomchristie** [comment]
Pushing all further HTML specific stuff to 3.2.0.

**Comment by rerobins** [comment]
Is it possible to add an option to remove the form content from the bottom of the browsable API?  

I'm attempting to do some performance testing on my pages (using django-debug-toolbar).  First step was to reduce the number of queries that I am executing in my views.  The form that is displayed at the bottom has the potential to implement 3x more queries than the JSON renderer does.  

I've worked around this by extending the BrowsableAPIRenderer and overriding the get_raw_data_form method to return None.  I did this because I couldn't find a setting that would provide this functionality for me.  

Am I missing a better way of implementing this functionality?  I don't want to turn the forms off completely, just during some of my performance testing.

**Comment by tomchristie** [comment]
Dropping this ticket - too specific at this point.
We'll do some general clean up for the browsable API and admin API, but can happen after 3.3.0, and we'll decide at that point what the clean up priorities actually are.

**Comment by Antwan86** [comment]
I know this is closed, but can you pingback the future discussions in this ticket ? I've made some generic improvements in my apps which might be worthwhile regarding this, and I'd like to contribute to discussions when this will happen.
Thanks !

**Comment by tomchristie** [comment]
> can you pingback the future discussions in this ticket ?

Can't promise to remember, but no objection otherwise, sure. :)
