### ISSUE TITLE
Serializer missing context if pagination is used.

### ISSUE THREAD

**Issue by flc** [tomchristie/django-rest-framework#2355]
affects all versions of drf3; worked in drf2

suppose we have an app called 'text' with a models.py (i've just put everything there for simplicity):

```python
from django.db import models
from rest_framework import viewsets, serializers
from rest_framework.test import APITestCase

class Text(models.Model):
   text = models.TextField()

class TextSerializer(serializers.ModelSerializer):

   def __init__(self, *args, **kwargs):
      super(TextSerializer, self).__init__(*args, **kwargs)
      print 'Context in serializer', self.context

class TextViewSet(viewsets.ModelViewSet):
    queryset = Text.objects.all()
    serializer_class = TextSerializer

class TextViewSetWithPagination(TextModelViewSet):
    paginate_by = 10
```

opening a shell:
```python
In [1]: from rest_framework.test import APIRequestFactory
In [2]: from text.models import *
In [3]: TextViewSet.as_view({'get':'list'})(APIRequestFactory().get('/'))
Context in serializer {u'view': <text.views.TextViewSet object at 0x5fba390>, u'request': <rest_framework.request.Request object at 0x5fba650>, u'format': None}
Out[3]: <rest_framework.response.Response at 0x5fdb2d0>
In [4]: TextViewSetWithPagination.as_view({'get':'list'})(APIRequestFactory().get('/'))
Context in serializer {}
Out[4]: <rest_framework.response.Response at 0x7fe8dd0>
```

**Comment by tomchristie** [comment]
Reopening for re-assessment based on this comment...

> the context still {} or None, when the object_serializer() init

**Comment by vplme** [comment]
`object_serializer()` is  instantiated in the `BasePaginationSerializer` which calls the `def __init__` of the object_serializer (in this case `TextSerializer.__init__`)
 Since `bind()` is called after instantiation of `object_serializer` the context is not yet available in `object_serializer.__init__`.

 Maybe the context needs to be passed directly to object_serializer? (e.g. `object_serializer(context=self.context)`).
 `generics.GenericAPIView.get_serializer()`  seems to do the same and also passes the context as a parameter (in kwargs). 
 [generics.GenericAPIView.get_serializer()](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/generics.py#L82-L89)
