### ISSUE TITLE
unhelpful error message from incorrect format of serializer field validators argument

### ISSUE THREAD

**Issue by robbyt** [tomchristie/django-rest-framework#2372]
I attempted to create a serializer field with the validators argument set to a string inside a tuple. Obviously this is incorrect, but it was not easy to debug because the stack trace shows that the error is coming from the `post` method on the view, not from the `.is_valid` call. If you call `.is_valid` directly, it throws the type error.

```python
      organization = serializers.SlugRelatedField(                                 
          slug_field='slug',                                                       
          queryset=Organization.objects.all(),                                     
          required=True,                                                           
          validators=('validate_organization_unique',),           
      ) 
```

`*** TypeError: 'str' object is not callable`

**Comment by tomchristie** [comment]
Don't do that.

**Comment by tomchristie** [comment]
For more context, closing because I think it's super important that we focus 100% on the headline functionality for 3.1 and 3.2 at this point in time. We can re-consider minor tweaks like this once we've got that all complete. Until then it's no sustainable for us to pick up on trying to enhance every possible mis-use case.
