### ISSUE TITLE
TokenAuthentication incompatible with a custom user model without username

### ISSUE THREAD

**Issue by protactinium** [tomchristie/django-rest-framework#2392]
In case a custom user model is implemented without a username (in my case I only rely on the user email address as the primary field), Token Authentication does not work with the error:

```
{"username":["This field is required."]}
```
The code that raises this error is in *django-rest-framework/rest_framework/authtoken/serializers.py*

```python
if username and password:
            user = authenticate(username=username, password=password)
````
I have edited this file to corresponds to my specific case, but I suppose that it is better to have a general solution; thus the creation of this ticket.

Thanks for the great work

**Comment by tomchristie** [comment]
I think we should push this into the 'customize the TokenAuthenication class yourself to get that functionality' rather than do something generic in REST framework. Not clear to me that the trade-off of extra complexity would be worth it, vs keeping the simplest possible solution as our included implementation.

I'd be very happy to reconsider, but only if someone else wants to actively create a pull request with a possible solution to the more general case, so that we can review a concrete alternative on it's own merit.

Sorry to disappoint - hope the motivation behind this resolution makes sense to you.

**Comment by philippeluickx** [comment]
+1 on having the functionality if gracefully done. I am using allauth where you can have the option to either use the email or username. But somehow I have the impression that this is either done through customization or should be Django core to solve...
