### ISSUE TITLE
Create or update relation via RelatedField + using parent data

### ISSUE THREAD

**Issue by stevelacey** [tomchristie/django-rest-framework#2409]
Okay, rubbish issue, I know, sorry, but I can't work out how I am "meant" to implement this in DRF 3 and I figure it'll be useful for someone else anyway:

```py
from django.core.exceptions import ObjectDoesNotExist
from acme.accounts.models import Organisation
from acme.archives.models import Tag
from rest_framework.relations import SlugRelatedField

class TagRelatedField(SlugRelatedField):
    """A read-write field that represents a tag and creates it if it does not exist"""

    def to_internal_value(self, data):
        try:
            organisation = Organisation.objects.get(
                code=self.parent.parent.data['organisation']
            )

            fields = {
                self.slug_field: data,
                'organisation': organisation
            }

            try:
                tag = self.get_queryset().get(**fields)
            except ObjectDoesNotExist:
                tag = Tag(**fields)
                tag.save()
            except (TypeError, ValueError):
                self.fail('invalid')

            return tag
        except ObjectDoesNotExist:
            pass
```

This just about works in DRF 3.0.1 but is a bit whacky and exhibits one bug I am aware of, and as of 3.0.3 moans about the `is_valid` stuff and using `initial_data` instead which I see has changed to stop me doing this because it's whacky.

The bug I am aware of: stale tags after PUT/PATCH, the response to those requests shows the old tags, but subsequent GETs don't, which I can only assume is because the forms data is populated before the point I am hooking into. I could just patch the form's data... but that is one whack too far IMO.

My question, is how am I /supposed/ to implement this?

- Tags are exposed like this: `{...tags: ['a', 'b', 'c']}`
- On create/update of the parent tags that exist are related to it
- On create/update of the parent tags that do not exist are created and related to it.
- All tags are related to an organisation, which is a field (relation) specified on the parent and exposed by a SlugRelatedField

**Comment by tomchristie** [comment]
> Okay, rubbish issue, I know, sorry ... but that is one whack too far IMO.

:)

I'm going to close this off in it's current state as it's a usage question rather than a bug report, but don't take that as closing the issue off to discussion - more than willing to help out if possible.

The issue will be *something* to do with this...

> tag.save()

You're conflating the validation, with the object save (which should happen entirely after the validation).
Saving the serializer calls `.create()` or `.update()` which is what populates `self.instance` which is used when serializing the object again.

I'd assume that something about the style you're using means that `self.instance` isn't being correctly set, and is instead an out of date object instance.

Of course if that's not enough to go on, you're still finding this problematic, *and* you're able to reduce this to a smaller example case that you think demonstrates problematic behavior then we can consider looking at it as an issue again, but I think you're most likely into trying-to-debug-this-perhaps-with-some-help-on-the-discussion group.

It does *potentially* look like one of those sorts of areas where we might try to restrict the API further and/or add code that tries to catch the incorrect usage, so it'd be worth keeping this thread updated with your resolution so we can decide if there is any combination of documentation and/or safety checks that we ought to be doing that we're currently not.

Alternatively perhaps there really are ways that a valid serializer can end up with a stale object instance on `self.instance` - in which case we should look at that, although *currently* I've no reason to believe that to be the case.

**Comment by stevelacey** [comment]
Yeah I realise this isn't really what GitHub issues are for, but the chances of getting anything useful out of StackOverflow on such a specific use-case with a particular new version of a particular library is pretty slim, and I know you're in the process of making some pretty significant changes to DRF in v3 anyway.

I think you're answer to my problem is from the perspective that I have a TagSerializer, which I don't, should I? I chose not to use a serializer after experimenting, and finding no way to represent a serializer in the way I needed (basic array of strings), let alone handling the idea that creation of new tags from within the serializer of another model is acceptable.

SlugRelatedField seemed to encapsulate a majority of the functionality I require, just missing the creation stuff.

What I am really looking for is a little guidance on at what point I should be making the conversion to/from Tag instances – or whether my approach of extending SlugRelatedField is even the way to go?

**Comment by tomchristie** [comment]
I'm not sure exactly how you're using `TagRelatedField` so hard to say - I was assuming it was a field that you were using on a serializer class. Not a *problem* that it's not, but you'probably do best just removing the extra layers of abstraction that you're getting with the field class and just write the behavior into the view explicitly, or else use `BaseSerializer` to give you a simple wrapper that you can write the validation logic into.

**Comment by stevelacey** [comment]
Sorry, it is just a field on a serializer class. I guess I could move it out to the view, but is that easy to do in a DRY manner given I want the functionality available for all CRUD? I actually don't care much about validation, I simply want to suppress any "object not found" stuff and replace it with creation, and by the sounds of it, validation simply isn't the place to do that.
