### ISSUE TITLE
Upgrade from 2.4.x to 3.x

### ISSUE THREAD

**Issue by spapas** [tomchristie/django-rest-framework#2542]
I recently tried to upgrade my 2.4.x ``djangorestframework`` installation to 3.x. I experienced many, many problems - more than I'd like to share in this issue. I tried finding resolutions for them to the release notes of 3.x (or elsewhere on the net) but didn't find anything. I lost more than an hour of my time and as a result I just lost my confidence and got back to 2.4!

I think that you either need to expllicitly say somewhere **Don't upgrade from 2.x to 3.x, just create from scratch all your serializers, viewsets, permissions etc** or mention *everything* that has been changed and is no longer working. 

I know that by changing the major version number you can do whatever breaking changes you want, however I feel that you need to think of your users also - don't torture us! 

(really sorry for the ranting)

**Comment by xordoquy** [comment]
@spapas I've already seen a couple of migrations that went well though requiring some work - your mileage may vary.
The 3.0 annonce does list what has changed (http://www.django-rest-framework.org/topics/3.0-announcement/).
If it is missing informations please let us know exactly what's missing.
PS: please don't use the issue tracker as a forum. There is a mailing list or irc channel for arguing about those things.

**Comment by spapas** [comment]
You mention

> I've already seen a couple of migrations that went well though requiring *some work*

*Some work* is really arbitrary -- it may be some minutes for some people, some days for other people! So, not mentining in your documentation that upgrading requires *some work* (I'd say a lot of work but in any case) *is* an actual issue and not a dicussion topic.

Also, from the top of my head (I don't want to again install v. 3.x) , here are two of the issues I encountered:

1. I had created a ``ModelSerializer`` named ``RecurrentAvailabilitySerializer`` and I was using it from another serializer like this ``recurrentavailability_set = RecurrentAvailabilitySerializer(many=True, allow_add_remove=True, read_only=False)``. Version 3.x didn't like the ``allow_add_remove`` kwarg. I don't see anything for this mentioned in http://www.django-rest-framework.org/topics/3.0-announcement/

1. I had defined a ``ModelViewSet`` like this: 
```
class PermanentAvailabilityViewSet(viewsets.ModelViewSet):
    model = spots.models.PermanentAvailability
````

This worked fine in 2.x but in 3.x it complained that it needed a ``base_name`` or a ``queryset`` to find. I also didn't see it mentioned in the 3.0 announcement.

**Comment by tomchristie** [comment]
@spapas Understand that it's painful that we've made breaking changes. The serializers in 2.x had some fairly fundamental issues and it was unavoidable that we make the breaking changes in order to fix that. We've spent a long time working through all the changes and documenting everything as thoroughly as possible in the [3.0 announcement](http://www.django-rest-framework.org/topics/3.0-announcement/).

> 1. allow_add_remove

The removal and motivation behind no longer including (buggy) built-in support for writable nested updates (and instead requiring that they be handled explicitly) is described here... http://www.django-rest-framework.org/topics/3.0-announcement/#writable-nested-serialization You're right that it doesn't explicitly mention `allow_add_remove` - we could accept a pull request handling adding that in at a sensible point.

> 2. I had defined a ModelViewSet like this

This usage was deprecated [as part of 2.4](http://www.django-rest-framework.org/topics/2.4-announcement/#deprecation-of-model-view-attribute). That was an incremental change and will have raised a warning in 2.4, and stopped working outright in 3.0.

**Comment by JockeTF** [comment]
Since our company was doing quite a bit of special stuff in DRF 2 we've had to spend a lot of time upgrading to DRF 3. That is however time well spent. I am very pleased with the redesign as it makes building our system much easier in the long run. Almost every single change listed in the DRF 3 announcement was something that we had stumbled on in DRF 2.

After reading the DRF 3 announcement I haven't really had any surprises regarding what broke and what kept working. Either way, rewriting the system from scratch would have taken us way longer than our migration will.

To me, DRF 3 is a huge leap in the right direction for Django REST Framework.

**Comment by spapas** [comment]
@tomchristie thanks for clarifying the issues (and for djangorestframework - it's a really great library)!
@JockeTF thanks for the info ! 

 I'll probably keep 2.4.x for old (but supported) projects and use 3.x for new ones (or old ones that allow me to spend a lot of time upgrading to 3.x)

**Comment by tomchristie** [comment]
> I'll probably keep 2.4.x for old (but supported) projects and use 3.x for new ones (or old ones that allow me to spend a lot of time upgrading to 3.x)

Nothing wrong with that approach yes. Obv depends your business priorities.

The good news is that whereas before the project was kind of in a bit of a sticking point where there were a bunch of unresolvable problems, we've now got something that I see as being sustainable for the foreseeable future.
