### ISSUE TITLE
Consider allowing raising SkipField from to_representation

### ISSUE THREAD

**Issue by JockeTF** [tomchristie/django-rest-framework#2544]
It may be a good idea to allow raising SkipField not only from get_attribute, but also from to_representation. At the moment, [it is only possible to raise SkipField from get_attribute](https://github.com/tomchristie/django-rest-framework/blob/4b65e9e42be068ad3e742692262451f8836f09d3/rest_framework/serializers.py#L422-L432).

My use case for this is pretty special though. I am currently working on an [inline expansion](http://venkat.io/posts/expanding-your-rest-api/) package for DRF 3. Slightly delaying the decision about whether or not a field should be skipped could make things a little bit easier for me.

**Comment by tomchristie** [comment]
Given that we don't have any fields in core that'd use this I'm going to close this off, and nudge in the direction of overriding `to_representation` on a new base serializer class that you can then use throughout your application.

If anything we should be doing a better job of showing folks how they can write custom serialization styles using `to_representation`, rather than building more behavior into it ourselves.

**Comment by sparkyb** [comment]
I'd like to suggest re-opening this. I have this issue too. In my case, I'm using `SerializerMethodField` and I'd like my method to be able to raise `SkipField` to have the field omitted (in this case, it is data I only want included in the serializer if certain query parameters are set on the request). Having to override `to_representation` on my serializer (not just a field) seems like overkill.

Since the change would have be inside the inner `for field in fields` loop, I'd have to duplicate the entire `to_representation` method, not just the bit I want to patch. I might recommend that that inner block be moved into a `get_field_representation(field, instance)` so that it is more easily subclassed (would also help for the issue I'm seeing a lot where folks want `to_representation` called on `None` i.e. #2299). But that's a bigger change.

For this issue, it seems like it'd be fairly safe to just catch `SkipField` from `field.to_representation` and would help in my `SerializerMethodField` case. In the meantime, my workaround is will be either a custom field mixin that overrides `get_attribute` to raise `SkipField` earlier (kind of a hack since the check I'd be doing has nothing to do with getting any actual attribute), or subclassing my serializer's constructor and deleting the field if the necessary query params aren't included.

**Comment by rpkilby** [comment]
> or subclassing my serializer's constructor and deleting the field if the necessary query params aren't included.

This would be the preferred approach. I would remove the fields in `__init__` or `get_fields`.
