### ISSUE TITLE
Permissions docs should show example using generic views

### ISSUE THREAD

**Issue by foresmac** [tomchristie/django-rest-framework#2548]
Do I just override `permission_classes` on a generic view? If so, do I just include my custom permissions, or do I also need to include my default (e.g. `IsAuthenticated`)?

I can guess yes on the first one, but the second I cannot answer from the [information provided in the docs](http://www.django-rest-framework.org/api-guide/permissions/).

**Comment by tomchristie** [comment]
I think the example here is clear no?...

http://www.django-rest-framework.org/api-guide/permissions/#setting-the-permission-policy

No it doesn't include any defaults. It's either set globally, or specifically on the view. This is the same pattern we use throughout, and given that we haven't seen this usage question in the past I'm going to close this off, pending anyone else reraising this.

**Comment by foresmac** [comment]
So, if I have the following:

``` python
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'tokens.auth.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'PAGINATE_BY': 10,
}
```

and I set the following in a view:

``` python
class GetUpdateDeleteItem(generics.RetrieveUpdateDestroyAPIView):

    model = Item
    serializer_class = ItemSerializer
    permissions_class = (IsOwnerOrReadOnly, )
    queryset = Item.objects.all()
```

then if I also want `IsAuthenticated` applied to the view, or only `IsOwnerOrReadOnly`?

I'd expect the former, but it sounds like you are saying it's the latter. Like I said, I can't honestly be sure from the docs.

**Comment by tomchristie** [comment]
We've not had the question before, and it's been like that since forever (and throughout all the different components in REST framework), so I'm not *especially* minded to prioritize changing the docs here at the moment. Happy to re-review this if either:

1. We see the same question being asked again.
2. Someone issues a pull request changing the style throughout the components consistently to make it more explicit that these are overriding the default. We could then review that PR on it's own merit.

**Comment by foresmac** [comment]
Duly noted. Thanks.
