### ISSUE TITLE
parser not given the chance to parse an empty request body

### ISSUE THREAD

**Issue by amc1804** [tomchristie/django-rest-framework#2556]
Completely-empty JSON requests (which are not valid JSON) are rejected by the browsable API but accepted by the production API, which confuses debugging attempts.

In request.py, if stream is None, the parser is not invoked, and an empty DATA is created. I don't know why an empty request body is represented as None rather than an empty stream, but if the parser had been given a chance to parse an empty stream, it might have yielded something other than empty DATA.  For example, the JSON parser raises a ParseError.

In the browsable API, where requests are tunneled through forms, the parser does get invoked (and in the case of JSON, does reject an empty request).

Bypassing the parser for empty requests allowed a bug in Firefox 35 to cause data loss.

https://bugzilla.mozilla.org/show_bug.cgi?id=1128038

The browser bug sometimes truncates a PATCH request to zero length.  The rest framework turns this into empty data instead of a parse error, the application code applies the no-op patch and returns 200 OK, and the user is not alerted that the data was not actually saved.

Perhaps, rather than construct an empty DATA, the framework should construct an empty stream, and let it be parsed normally.

(By the way, many thanks to Tom and all contributors.  This framework has been very helpful!)

**Comment by tomchristie** [comment]
If there's no request body to parse, we don't parse the request body.

I don't see us changing this behavior - it's not unreasonable to ignore the 'Content-Type' header if no content is included in the request.

> The rest framework turns this into empty data instead of a parse error

This should be handled at the serializer level - which should fail with a validation error. "no data was provided" or "expected a dict but got None" or similar. I believe we already do this, but if not it would be a valid issue to consider.

> In the browsable API, where requests are tunneled through forms, the parser does get invoked

Indeed, although I'd consider that an artifact of the browsable API rather than the desired behavior.

**Comment by amc1804** [comment]
Tom Christie <notifications@github.com> wrote:

> I don't see us changing this behavior - it's not unreasonable to ignore
> the 'Content-Type' header if no content is included in the request.

Okay.

> > In the browsable API, where requests are tunneled through forms, the
> > parser does get invoked
> 
> Indeed, although I'd consider that an artifact of the browsable API
> rather than the desired behavior.

Then maybe the discrepancy should be resolved the other way:  An empty
request tunneled through forms should also bypass the parser, just like
a non-tunneled request.  The way it is now is confusing when one is
trying to use the browsable API for debugging and the behavior doesn't
match what was observed in production.

> > The rest framework turns this into empty data instead of a parse error
> 
> This should be handled at the serializer level - which should fail with
> a validation error. "no data was provided" or "expected a dict but got
> None" or similar.

It was a many=True serializer, which was expecting an iterable, and
that's what it got.  When request.py encounters a missing stream, it
creates DATA as an empty iterable.  How do you recommend the serializer
to distinguish between valid JSON [] versus an invalid empty request
when both are represented by an empty iterable?

Thanks,
AMC

**Comment by Opalo** [comment]
> This should be handled at the serializer level - which should fail with a validation error. "no data was  provided" or "expected a dict but got None" or similar. I believe we already do this, but if not it would be a valid issue to consider.

Actually it doesn't make any sense to ignore empty body and pass it directly to handler. If I use `parser_classes` (my custom implementation to validate incoming body with JSON schema) decorator I expect this parser to be **called**, **parse** and **validate** the incoming body. Currently I've to.. check it twice, which is a complete nonsense.  If body isn't empty it will be validated automatically, otherwise I've to check it on my own. Serializers are not a good solution to every problem because they're tied to model and not in every case model is exactly what is received/returned via request/response.

**Comment by elnygren** [comment]
> they're tied to model and not in every case model is exactly what is received/returned via request/response.

```
class SomeSerializer(serializer.Serializer):
  field1 = serializer.someFied()
  field1 = serializer.someFied()
```
The above is not tied to any models. You can use it to validate a request. The view using this could call `serializer.is_valid(raise_exception=True)` to validate. 

> called, parse and validate the incoming body.

Shouldn't a parser just parse ? Validation should always be done in a serializer. Empty body -> nothing to parse -> no need to even call the parser.

**Comment by Opalo** [comment]
@elnygren if an instance of `Serializer` isn't tied to model then how you can refer the data after serialization? Because I'm getting exception saying: `{AttributeError}'SomeSerializer' object has no attribute 'field1''`. This make serializers not usable because I don't want to have them tied with models. I've used custom JSONSchemaParser that was checking if payload is valid.

**Comment by denis-sumin** [comment]
I'd vote for this issue: consider it reopening and having an option to give the parser even empty request data.

I'll give the reasoning with an example from my current project. I have a parser for (google) protobuf data. A protobuf message with all default field values will have a 0-bytes representation. And since it is a valid serialized presentation of a protobuf object, I'd like to be able to parse it with my protobuf parser.

I could try to implement such option for parsers if there will be support from the community. Do you think that my case is worth considering?
