### ISSUE TITLE
Documentation for searching of ViewSets

### ISSUE THREAD

**Issue by ryan-blunden** [tomchristie/django-rest-framework#2590]
# Problem statement
Looking at the 3.0 docs, it's unclear if searching will work on a `ViewSet`, or if I have to use a GenericView class.

## Explanation
The documentation at http://www.django-rest-framework.org/api-guide/filtering/#searchfilter gives an example using `generics.ListAPIView` as the parent class. 

If I read all the documentation on the ViewSet page, I would know that it will work as `ModelViewSet` class inherits from `GenericAPIView` but this certainly wasn't obvious to me when first reading through the docs on the search page.

## Proposed Solution
What I'd like to see is the `/api-guide/filtering/#searchfilter` section of the documentation include an example for searching on a class that inherits from a ViewSet.

**Comment by tomchristie** [comment]
We do this all the way through - viewsets are just views that do not yet have their actions bound to a particular method. I *would* consider pull requests against this, or pull requests deal with this through the documentation more comprehensively, but I'm not otherwise going to treat this as an outstanding issue.
