### ISSUE TITLE
Loose closing brackets inserted at the start of the JSON, for my Django Rest Framework endpoint.

### ISSUE THREAD

**Issue by AncientSwordRage** [tomchristie/django-rest-framework#2599]
I'm getting this strange set of closing brackets/parenthesis at the start of all of my JSON endpoints. Example is given below:

```
)]}',
{"id":1,"username":"admin","mage_by_user":[3],"mage_last_updated":"2015-02-11T16:13:16.229Z"}
```

This code is [here](https://github.com/AncientSwordRage/nWoD-db) and should reproduce it.

Here is an SO [question](http://stackoverflow.com/q/28700626/1075247) about it.

**Comment by tomchristie** [comment]
This isn't framed as a valid issue - simply linking to a repository means we'd have significant work to do in order to unpick whatever it is you're referring too. Strongly suspect this to be a user issue, so we'd need some further confirmation or more work on your side investigating and narrowing this down to eg a reproducible test case, before I'd be willing to invest time in it.

**Comment by AncientSwordRage** [comment]
For anyone else coming here, it's inserted by Djangular, but not stripped off by JSONViewer (see: gildas-lormeau/JSONView-for-Chrome#21 )
