### ISSUE TITLE
Wrong self.request.method in get_serializer_class

### ISSUE THREAD

**Issue by bryanph** [tomchristie/django-rest-framework#2663]
When doing a get request on the registered url in the view shown below, the self.request.method in get_serializer_class prints 'POST'.  

When removing the get_serializer_class, the get method is called appropriately.

```python
COLLECTION_TYPES = {
    'iati': CollectionSerializer,
}

class CollectionList(generics.GenericAPIView):
    """
    List and create collection
    """
    model = collection_models.Collection
    queryset = collection_models.Collection.objects.all()

    def get(self, request, *args, **kwargs):
        print('called')

        results = list()

        for collection in self.queryset:
            serializer = COLLECTION_TYPES[collection.type](collection)
            results.append(serializer.data)

        return Response(results)

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer_class(request)(request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    def get_serializer_class(self, request):
        print(self.request.method)
        if self.request.method in ('POST'):
            return COLLECTION_TYPES.get(self.request.data.type)

```

**Comment by tomchristie** [comment]
This isn't presented as an actionable issue.

If you would like us to invest time in determining if there's a problem that needs addressing then you'll need to first put in some work into nailing this down to it's simplest possible example case - ideally with a test case.

In it's current form we don't have any way of differentiating this from a usage issue, and wasting time on something that we can't verify.

**Comment by tomchristie** [comment]
Apologies that we can't spend tim eon it without further initial investigation on your part, but experience has shown that it's not worth our time looking at issues presented as "heres my code sample from my project, without modification", at least until they're presented in a more readily verifiable form.

**Comment by dodekeract** [comment]
@tomchristie @bryanph

The same happens in my codebase. I'm pretty sure that it's related to the form that gets rendered when using a browser to use the API. It doesn't happen via Paw with JSON.

To me it seems like Django tries to find out which fields the serializer uses so that the form can be  rendered, but to do that it "simulates" a `POST` request.

**Comment by Fogetti** [comment]
Exactly, this has been closed too early and it's still happening. Something is definitely wrong how DRF handles and sets the `request.method`.

**Comment by rpkilby** [comment]
If someone could reduce this to a simple test case (preferably submitted as a failing PR), then this is something we could look into.

**Comment by xordoquy** [comment]
@FlorianWendelborn has the correct explanation.
Browsable API needs to get the serializer associated with a POST request in order to display its associated form. It will also check permissions to ensure the user is allowed to use that action.
For that, it needs to simulate a POST request to get all those informations.
No need to write a test case for that or reopen that issue although a word about this in the documentation could be nice.
