### ISSUE TITLE
Package caching on travis

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2677]
See https://twitter.com/ghickman/status/575974883647209473

**Comment by jpadilla** [comment]
Oh yeah, gonna give that a try!

**Comment by xordoquy** [comment]
Was going to suggest it though I didn't fully understand the improvements.

**Comment by thedrow** [comment]
I tried in #2564 but it actually slowed down the build.

**Comment by tomchristie** [comment]
Yeah - couple more things in @ghickman's change.
Not going to claim to understand the changeset myself, but may be worth another go with the `PIP_WHEEL_DIR`, `PIP_FIND_LINKS` and `pip wheel` changes?

**Comment by ghickman** [comment]
Just popping in to say that work is all @dstufft's! I simply used his example (the one I linked to) =).

**Comment by konradko** [comment]
[Wheels caching with tox on Travis](https://github.com/tomchristie/django-rest-framework/pull/2746) turned out to be slower than simple ``pip install``, as each tox env required a separate wheelhouse (``export WHEEL_DIR=$HOME/.wheelhouse/`` after ``pip install tox`` in ``install`` section) to avoid conflicts. I'll try with this approach: https://pip.pypa.io/en/latest/user_guide.html#fast-local-installs

**Comment by tomchristie** [comment]
Going to close the issue off dead - that makes sense at this point, right @konradko?

**Comment by maryokhin** [comment]
@tomchristie What's will all the die hard tries to get Travis caching? To me the build times are precisely timed for the walk to the kitchen for a cup of coffee :relieved:

**Comment by tomchristie** [comment]
:p

**Comment by thedrow** [comment]
Shorter build times means less coffee so it's for your well being. :+1:

**Comment by konradko** [comment]
@tomchristie 

I'll give it one last try this evening with 'selective' caching of packages identified as large (e.g. django).

**Comment by tomchristie** [comment]
@konradko glutton for punishment

**Comment by konradko** [comment]
:P

tox creates multiple environments, each with separate set of packages to cache in it. These cannot be shared between venvs as wheels because of naming conflicts. Storing them separately increases the Travis cache so much that the time gained from quicker install is lost on the cache download. Syncing uncompiled (non-wheel) pip cache from Travis turned out to take similar time as just downloading the packages from pip. It looks like at the moment Travis caching is only useful for projects with dependencies that are slow to download in comparison to fetching them from S3 (where Travis cache is stored) or if pre-compiled packages can be used.
