### ISSUE TITLE
conflict with context argument passing on HyperLinkIdentityField

### ISSUE THREAD

**Issue by Karmak23** [tomchristie/django-rest-framework#2693]
Hi, I'm having trouble making a model serializer with a GFK.  I'm using DRF 3.1.0.

(I already read http://stackoverflow.com/q/14448764/654755) 

Given [this model](https://github.com/1flow/1flow/blob/master/oneflow/core/models/reldb/processor/chaineditem.py#L66) and this serializer:

```python
class ChainedItemSerializer(serializers.HyperlinkedModelSerializer):

    """ ChainedItem serializer. """

    item = serializers.SerializerMethodField()

    def get_item(self, obj):
        """ Turn a [GFK] processor or processing chain into an API URL. """

        item = obj.item

        serializer = serializers.HyperlinkedIdentityField(
            source=item, view_name='%s-detail' % slugify(unicode(
                item._meta.verbose_name)).replace(u'-', u''))
        # , context={'request': self.context['request']})
        
        return serializer.to_representation(item)

    class Meta:
        model = models.ChainedItem
        exclude = []
```

Instanciating `HyperlinkedIdentityField` without the `context` argument, it raises `HyperlinkedIdentityField requires the request in the serializer context. Add context={'request': request} when instantiating the serializer.`, which seems fair regarding the DRF documentation and the questions you answered on S.O.

But then, uncommenting the `context` argument passing, it complains `__init__() got an unexpected keyword argument 'context'` (see [full stacktrace on my sentry](http://dev.1flow.net/development/1flow-dev/group/55759/)).

Having read all classes `__init__` code (in master branch) from `HyperLinkIdentityField` up to `Field`, it seems none of them takes care of `kwargs['context']` nor records it anywhere.

Trying to set `serializer.context = …` manually between `__init__()` and `to_representation()` obviously raises `can't set attribute` (sorry for even having tried that ;-) ). 

Seems I'm stuck. What am I missing ?

**Comment by maryokhin** [comment]
I think you got mixed up there, you're supposed to pass the context from the view to your `ChainedItemSerializer`, not setting it inside the serializer. If you are using a generic view, then this should already be done for you, because they have a special <a href="https://github.com/tomchristie/django-rest-framework/blob/4248a8d3fc725d9ae3fe7aaaad7ee12479ab07ab/rest_framework/generics.py#L129">`get_serializer_context()`</a> method that you can override for setting custom stuff.

**Comment by Karmak23** [comment]
Yep, I use a generic view, that's why I don't understand why the context is not forwarded. The View:

```python
class ChainedItemViewSet(viewsets.ModelViewSet):

    """ ChainedItem model. """

    permission_classes = (IsAdminOrReadOnly, )
    queryset = models.ChainedItem.objects.all()
    serializer_class = ChainedItemSerializer

```

**Comment by tomchristie** [comment]
> But then, uncommenting the context argument passing, it complains __init__() got an unexpected keyword argument 'context' (see full stacktrace on my sentry).

If there's an error where a valid serializer fails when `context` is passed to it on instantiation, then we can treat that as a bug and resolve it, but as currently reported this issue is insufficiently narrowed down to determine if there's actually a bug here, a documentation problem, or if this is a usage issue.

**Comment by Karmak23** [comment]
@tomchristie I though the non usage-related issue state was cleared out by my answer to @maryokhin and all the pretty simple code I gave. `context` is not taken care of by the field, whereas the exception message tells me to pass it to the field.

As I'm not a DRF internals expert, I was asking you to arbitrate which kind of issue it is between doc & bug.

**Comment by tomchristie** [comment]
We need folks to help us narrow down valid issues by putting in some work their side.

I totally appreciate that's not always easy for newcomers, but the alternative is that we spend a lot of time looking into things that may not be worth our attention, at the expense of not being fully focussed on the existing and large set of identified and readily actionable issues.

From a brief look over your issue you're working with the API in a way that's not really intended. This line... `serializer = serializers.HyperlinkedIdentityField(...)` ...is awkward because you're not creating a serializer there, you're creating a field. As it happens you can set the context using `field.bind(...)` which you may want to have a look at although note that it is private API.

**Comment by Karmak23** [comment]
OK. It seems the GFK is a mine of awkward usages ;-)
I will try this and follow-up here. Thanks for the hint !
