### ISSUE TITLE
Create Constants for HTTP Methods

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2721]
For example, see usage here: https://github.com/tomchristie/django-rest-framework/blob/74506ba8eda8fd813ff9d6353fcf2ba3b895bd13/rest_framework/permissions.py#L90

**Comment by kevin-brown** [comment]
I'm curious what the reasoning behind doing this would be. The HTTP methods are defined in the HTTP specification (always must be uppercase), and it's not like they're unclear (like the HTTP status codes).

**Comment by cancan101** [comment]
Why are the methods [shown here in the docs](https://github.com/tomchristie/django-rest-framework/blob/33cfc2e486fb70595d84f3c7a06f09c62fc68535/docs/api-guide/routers.md#extra-link-and-actions) (and it works in practice):  lower case?

**Comment by tomchristie** [comment]
The methods there are case-insensitive, you can use either style.

**Comment by kevin-brown** [comment]
It's important to mention that while the HTTP verbs [must be uppercase](https://github.com/mgonto/restangular/issues/955#issue-50069724), Django and DRF [will always call `lower`](https://github.com/django/django/blob/35b3158d52a5fe51d3b52aec1109a30a73c5abe9/django/views/generic/base.py#L84) on the string when determining what method to call (because Python uses `snake_case` usually).

**Comment by cancan101** [comment]
It might be worth making some note of this in the docs. I was confused when I saw lower case in one place and uppercase in others.

**Comment by dashdanw** [comment]
@kevin-brown to address your first question, it's hard for someone to trust that the function will work because it's unclear that it's case insensitive. It's not necessarily apparent via the docs or the code itself, and the fact that you can't get it to 'misbehave' even when you type it all upper and all lower can make people feel uneasy when integrating it with important business logic. I've definitely felt this way before.
