### ISSUE TITLE
Exceptions caused during accessing request.data are not re-raised on subsequent access.

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2799]
`rest_framework.request.request.data` is not idempotent. It may raise an exception the first time it is called but then return an empty dict the second time. This is due to how the `_parse` method is written:
```python
        try:
            parsed = parser.parse(stream, media_type, self.parser_context)
        except:
            # If we get an exception during parsing, fill in empty data and
            # re-raise.  Ensures we don't simply repeat the error when
            # attempting to render the browsable renderer response, or when
            # logging the request or similar.
            self._data = QueryDict('', encoding=self._request._encoding)
            self._files = MultiValueDict()
            self._full_data = self._data
            raise
```
where it will re-raise the exception but also set a number of fields that will be used the subsequent times  that data is called:
```python
    @property
    def data(self):
        if not _hasattr(self, '_full_data'):
            self._load_data_and_files()
        return self._full_data
```

Here is a test case that demonstrates the issue:
```python
        request = mock.MagicMock()
        negotiator = mock.MagicMock()
        negotiator.select_parser.return_value = JSONParser()
        request = rest_framework.request.Request(request=request, negotiator=negotiator)
        request._stream = mock.MagicMock()
        request._stream.read.return_value.decode.return_value = u''

        with self.assertRaises(ParseError):
            request.data

        with self.assertRaises(ParseError):
            request.data
```

**Comment by xordoquy** [comment]
Interesting !

**Comment by tomchristie** [comment]
I believe Django has the same exception behavior as this around accessing `request.POST`/`request.FILES`.

It *might* be a marginal improvement if we re-raised on subsequent access, but I'm not 100% convinced.
We've raised an exception - the application should handle it, or (more typically) allow it to work it's way through to the exception handler. That subsequent accesses will return empty data seems acceptable to me.

Currently I wouldn't deem this a clear enough case to warrant further attention. Could reconsider if someone wants to proactively put together a pull request for it, otherwise I'd say we should treat this as acceptable.

**Comment by cancan101** [comment]
FWIW This does make using a debugger difficult as the order of when you run code vs use watch statements means what you see can change.
