### ISSUE TITLE
M2M model field without `blank=True` should map to a serializer relationship with `allow_empty=False`.

### ISSUE THREAD

**Issue by marccerrato** [tomchristie/django-rest-framework#2804]
The Django 1.8 system check framework displays the warning [fields.W340]( https://docs.djangoproject.com/en/1.8/ref/checks/#related-fields) when the `null` parameter is defined on a `ManyToManyField`, since it has no effect.

This `null` field affects on whether a related field in a model serializer is considered required or not. We can see it [here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/field_mapping.py#L226-L227).

From my point of view, this behavior is correct for a `ForeignKey` but not for a `ManyToManyField`, that should be considered not required by default.

Adding the var `to_many` to the condition on the aforementioned code might do the trick.

**Comment by normanjaeckel** [comment]
See test in #2674.

**Comment by pdr** [comment]
+1

**Comment by tomchristie** [comment]
> should be considered not required by default.

For both this and #2674 I'm unsure *exactly* what behavior you're expecting.
M2M fields default to required, because the input field itself is required, although *it may be an empty list*.

Are you expecting to be able to provide `null` as the input for the M2M field, or are you seeing an issue when providing an empty list?

As currently described the existing behavior seems correct to me - require the input, but allow it to be an empty list.

**Comment by normanjaeckel** [comment]
See my answer in #2674. If `required=True` (the default) the framework should not accept empty lists/arrays. This is because the framework should behave like Django forms and here we got an error if we try to send an empty list to a required form field.

(The other point (not this issue) is that the required flag should be controlled by the model field option `blank` which is not the case at the moment.)

**Comment by marccerrato** [comment]
I agree with https://github.com/tomchristie/django-rest-framework/pull/2674#issuecomment-105479180

**Comment by emanuelschuetze** [comment]
+1

**Comment by tomchristie** [comment]
Retitled more appropriately.
The behavior that's being requested here as far as I understand it is to mirror Django's blank model field -> required input.

I'm not 100% convinced that we want `ManyToManyField(Something)` to always require >= 1 entry and `ManyToManyField(Something, blank=True)` to allow empty lists, and I'd really like to see that discussion pushed to the mailing list, but *certainly* we should at least allow either case to be specified.

If we do change the behavior we should do so in a major version bump and call it out prominently.

Requires #2250 as a prerequisite.

**Comment by ideallical** [comment]
+1

**Comment by tomchristie** [comment]
Accepting this, though given the potential for backwards incompatibility it's probably a good idea if we push it in 3.2.0, to allow us to call it out.

**Comment by tomchristie** [comment]
Also note that `allow_empty` is now a valid flag.
You can workaround the behavior here by using `extra_kwargs = {'my_field': {'allow_empty': False}}`.

**Comment by normanjaeckel** [comment]
Still open: Setting the M2M model field with blank=True does not set required=False as expected. (M2M fields with blank=False work as expected).

**Comment by tomchristie** [comment]
Not sure I'd accept that as valid or not, but welcome to open it. Defiantly should be considered seperators in any case.
