### ISSUE TITLE
Bugs in serializers.ModelField.get_attribute() and serializers.ModelField.to_representation()

### ISSUE THREAD

**Issue by gwikle** [tomchristie/django-rest-framework#2812]
If you have an object with a custom model field and create a REST framework serializer for that object you can trigger two AttributeError exceptions during validation:

AttributeError: "'OrderedDict' object has no attribute 'the_custom_field'"
AttributeError: "'TheCustomFieldClass' object has no attribute 'attname'"

I tracked the first to serializers.ModelField.get_attribute() which doesn't handle the case when an OrderedDict is passed instead of an instance.  My fix looks like:
```
    def get_attribute(self, obj):
        return serializers.Field.get_attribute(self, obj)
```

I tracked the second to serializers.ModelField.to_representation().  It is expecting an instance as an argument but is actually passed the field value.  My fix looks like:
```
def to_representation(self, value):
        return smart_unicode(value)
```

I'm not sure if this second fix would work for all possible custom model field classes, though.

**Comment by tomchristie** [comment]
> I tracked the first to serializers.ModelField.get_attribute() which doesn't handle the case when an OrderedDict is passed instead of an instance.

I didn't understand this fully - could you demonstrate with an example?
Why and when would you pass an OrderedDict instead of an instance if serializing model instances?
Perhaps you meant to use `serializer = MySerializer(data=request.data)` (for validating input data) but accidentally used `serializer = MySerializer(<whatever>)` (for serializing "whatever")

> I tracked the second to serializers.ModelField.to_representation(). It is expecting an instance as an argument but is actually passed the field value.

The `get_attribute` override on `ModeField` actually ensures that the entire object is passed rather then the field attribute...

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1445-1448

Be helpful to see exactly what you were doing in this second case too.

I'm going to close for now, but will consider reopening once we've got a bit more info.
