### ISSUE TITLE
NullBooleanField implementation differs from Django's

### ISSUE THREAD

**Issue by LaundroMat** [tomchristie/django-rest-framework#2844]
I'm trying to post data from a default ModelForm to a DRF-powered API endpoint which uses a default ModelSerializer for the same model.

The NullBooleanField isn't being deserialized correctly. By default, the ModelForm renders the field as a select widget with 3 options (1=Null, 2=True, 3=False), and I _think_ it has something to do with the difference between how Django [handles the incoming data and copes with the 3 different values](https://github.com/django/django/blob/stable/1.8.x/django/forms/widgets.py#L567) and how DRF's [TRUE_VALUES,  FALSE_VALUES and NULL_VALUES](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L522) are not taking into account what ModelForm typically renders.

Is this by design, and does this mean I'd better change how ModelForm renders the field?

**Comment by xordoquy** [comment]
@LaundroMat This is definitively linked.
The thing is, Django can't figure wether you didn't provide a response or you responded false.
More generaly, Django wouldn't care wether the field is empty or blank and proceed with those two states as being the same. However this is an issue because the underlying intent isn't the same.

I think you could work this around with a regular `BooleanField` on the `ModelForm`.
Please feel free to reopen if this didn't work.
