### ISSUE TITLE
Invalid keyword model with generic views

### ISSUE THREAD

**Issue by bkg** [tomchristie/django-rest-framework#2896]
From the docs on generic views under [examples](https://github.com/tomchristie/django-rest-framework/blob/master/docs/api-guide/generic-views.md#examples), there is mention of support for passing a model keyword arg to `as_view()` like:

``` Python
url(r'^/users/', ListCreateAPIView.as_view(model=User), name='user-list')
```

However, that situation results in:

```
ListCreateAPIView() received an invalid keyword 'model'. as_view only accepts arguments that are already attributes of the class
```

Is this behavior still supported on 3.x or is a doc fix needed here?

**Comment by tomchristie** [comment]
Good spot - the documentation is incorrect.
We require the user to *explicitly* specify the queryset and the serializer_class.
The `model` shortcut has been on the deprecation path and is now entirely removed.

**Comment by maryokhin** [comment]
The `model` thing is just impossible to kill, keeps appearing again and again in the docs >_<

**Comment by bkg** [comment]
Any potential consideration in resurrecting or refining this particular shortcut? 

I rather like the ability to handle the simple case of serializing an entire model/queryset to a response without requiring a separate serializer class definition.

**Comment by tomchristie** [comment]
@bkg - No, although you could easily write a mixin that defines `get_serializer_class` and `get_queryset` and populates them automatically if the `.model` shortcut exists.

The problems with the `.model` shortcut staying in are:

* It complicates two of the methods in the REST framework codebase - `get_queryset` and `get_serializer_class` - that may only be by a few lines, but it's super important that those methos stay trivial so that it's as easy as possible for everyone to know exactly what they do when overriding them.
* It in means there's too many different ways too do things - this means less common shared knowledge and examples.
* Folks were often using it erroneously, for example having defined both a `.queryset` and a `.serializer_class` - which is meaningless. At the point it's problematic, because other developers won't know why it's there, and may assume it needs to be added (or left in) even though it has not use or meaning.

**Comment by bkg** [comment]
@tomchristie thanks for the reply, I appreciate you taking the time to explain your thoughts on this. Indeed, that is the approach I took with a mixin and `get_serializer_class()`.

**Comment by tomchristie** [comment]
> that is the approach I took with a mixin and get_serializer_class().

Great!
Similar conversation here: https://twitter.com/mattrobenolt/status/595704802530750464
Space for some useful tooling/package here if anyone's much motivated.
