### ISSUE TITLE
force_update should be used in ModelSerializer.update

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2944]
`ModelSerializer.update` just calls `instance.save()` which [per the Django docs](https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.Field.primary_key) 
>If you change the value of the primary key on an existing object and then save it, a new object will be created alongside the old one.

This means that if the Serializer exposes the primary key, there is silent insert of a new object.

**Comment by tomchristie** [comment]
PKs on ModelSerializer classes are read only by default.
If the user creates a writable PK field then they're going to need to handle the save behavior accordingly.
I'd be okay with having a brief docs sections on primary keys in the serializer fields docs, but it's not a priority for me. Pull requests accepted but otherwise I'm going to consider this closed.
