### ISSUE TITLE
About Serializer timezone!

### ISSUE THREAD

**Issue by istommao** [tomchristie/django-rest-framework#2953]
when i use ModelSerializer i find DateTImeField Display is wrong
and i USE_TZ in settings.py is True
so i look for reason  in djangorestframework

```py
class DateTimeField(Field):
    ...
    def to_representation(self, value):
        if self.format is None:
            return value

        if self.format.lower() == ISO_8601:
            value = value.isoformat()
            if value.endswith('+00:00'):
                value = value[:-6] + 'Z'
            return value
        return value.strftime(self.format)
```

I found that `to_representation` function does not convert DateTImeField to local time

so i try to work it out, i add some code like this

`value = timezone.template_localtime(value)`
Is there someone tell me Whether there is the problem in djangorestframework

**Comment by tomchristie** [comment]
> Is there someone tell me Whether there is the problem in djangorestframework

We're not able to accept open-ended issues like this, as they're not productive.
If after some further work you believe there's an issue and want to offer a suggestion of how the behavior should differ then we may be able to consider that.
Otherwise the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/django-rest-framework) is generally the right place for usage questions.
