### ISSUE TITLE
optional_login and optional_logout tags use django reverse rather than drf reverse

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#3005]
The `optional_login` and `optional_logout` tags use [django's `reverse` rather than drf `reverse`](https://github.com/tomchristie/django-rest-framework/blob/dbd23521656b366cbaa1382a0d222f8fe4e3a326/rest_framework/templatetags/rest_framework.py#L3). The request is available in both cases, so why not pass it through?

This allows a number of benefits such as:
* versioning support
* fully qualified URL

**Comment by kevin-brown** [comment]
Is this an issue? I thought DRF's reverse just makes it an absolute link, which should only matter with non-browser clients (which shouldn't be searching for the login link).

**Comment by cancan101** [comment]
It also adds versioning support.

**Comment by xordoquy** [comment]
The login views are left to django. There is no reason they should be versionned

**Comment by carltongibson** [comment]
Given the push to complete the kick starter goals, I'm going to close this. We can always come back to it if versioning login views becomes a priority.

**Comment by cancan101** [comment]
There are other advantages to using the versioning system / passing in the request. You can have the login end point on a different subdomain.

**Comment by shabble** [comment]
just bumped into this (`optional_login`) not showing in browseable API pages, and it turned out to be because I'd added the `rest_framework.urls` under a URLPathVersioned include, so plain django reverse() wasn't finding them, and they weren't getting rendered.

Easy fix is to just move them to be outside the versioned part of the urlconf, but I think it might be reasonable for them to at least work with versioning, if not explicitly support it.

Argument goes something like: The version (in your url) is that of your API, in which you promise that an endpoint somewhere will remain and behave the same. If you change your auth setup to something different, you'd check version and implement different behaviour.

Granted, since it's really just a passthrough to the django(-admin) login/logout views, I'm not sure that holds up, but it would be easy to put some shim views in that decided whether to pass to django or do other things if you wished.
