### ISSUE TITLE
Keeping values in browsable api on error

### ISSUE THREAD

**Issue by tredzko** [tomchristie/django-rest-framework#3024]
Values entered in the browsable api list view html form are currently cleared on an error. This means that a user would have to re-enter the entirety of what they put in before. Instead, the values should be kept so the user can remedy the incorrect fields and keep what they have already entered.

**Steps to reproduce:**

1. Navigate to browsable api list view page.
2. Enter some values into the html form fields, but leave some empty or invalid.
3. Post the form.
4. Error is produced.

This also occurs on detail view even though the form is already prefilled with information.

**Comment by tomchristie** [comment]
Yup clearly an issue that's worth addressing.

**Comment by jpadilla** [comment]
Thinking about tackling this one next. It'd definitely make using the browsable api way better.

**Comment by jpadilla** [comment]
First attempt at this. This is just making sure we pass data to the serializers used in `get_raw_data_form()` and `get_rendered_html_form()`. As you can see the `username` is missing from the raw data form and is `None` in the HTML form because since the serializer has an error `serializer.data` defaults to `serializer.get_initial()` which excludes fields with `empty` values. Ideas on how to proceed are welcomed.

<img width="988" alt="screen shot 2015-07-18 at 8 00 42 am" src="https://cloud.githubusercontent.com/assets/83319/8761517/24b75cd6-2d23-11e5-81fe-a4ddea4438a5.png">
<img width="973" alt="screen shot 2015-07-18 at 8 00 51 am" src="https://cloud.githubusercontent.com/assets/83319/8761518/24ba9dc4-2d23-11e5-8c8c-8a837c28b193.png">

**Comment by tomchristie** [comment]
Resolved :smile:
