### ISSUE TITLE
Setting for defining custom model field mappings

### ISSUE THREAD

**Issue by stucox** [tomchristie/django-rest-framework#3050]
Would be nice to have a setting to customise which serializer field type is used by default for a given model field type.

e.g. I’m using [Djangae](https://github.com/potatolondon/djangae/) which has a custom `ListField` type, which I’d like to always use DRF’s `ListField` by default. I can do it like this:

```python
from rest_framework import serializers

serializers.ModelSerializer._field_mapping[djangae.fields.ListField] = serializers.ListField
```

but then I need to put that somewhere where it’ll always be imported. Kinda feels a bit like a bit of a monkeypatch.

Would be awesome if I could do this in settings.py:

```python
REST_FRAMEWORK = {
    'CUSTOM_MODEL_FIELD_MAPPINGS': {
        'djangae.fields.ListField': 'rest_framework.fields.ListField',
    }
}
```

**Comment by xordoquy** [comment]
@stucox Since the Django application refactoring you have a perfect place for altering the `ModelSerializer`.
Please note that you should alter `ModelSerializer.serializer_field_mapping` as you can see in https://github.com/tomchristie/django-rest-framework/blob/dee5fb56479edc05cd0dcc827607696e58710eda/rest_framework/serializers.py#L1361

**Comment by stucox** [comment]
@xordoquy Where is this ‘perfect place’ for altering `ModelSerializer`?
