### ISSUE TITLE
read_only flag not clearly documented

### ISSUE THREAD

**Issue by nmgeek** [tomchristie/django-rest-framework#3064]
It's taken me quite a bit of reading of the DRF documentation to get some idea what the read_only flag is supposed to do.  I think somewhere (but not in the section about the read_only flag) it says that read_only fields will not be treated as fields in model objects and will be ignored when creating or updating these objects.  Is that the essence?  Could the documentation be updated to explain what it does when you set it?

**Comment by xordoquy** [comment]
This is covered in the [serializer fields documentation](http://www.django-rest-framework.org/api-guide/fields/#core-arguments) under the `read_only` part. The current phrasing sounds good enough to me:

> Set this to True to ensure that the field is used when serializing a representation, but is not used when creating or updating an instance during deserialization.

**Comment by tomchristie** [comment]
I'd be happy to accept a little more fleshing out of that explanation - don't much mind either way, but we could make it super-clear that this means it'll only be present in the API response output, but should not be included in request input.

Happy to accept PRs or suggestions for it but otherwise agnostic about if we keep this open or closed.

**Comment by nmgeek** [comment]
The section of the documentation titled, Specifying read only fields, does not include the important explanation proved by @xordoquy so it would be good to add it there: http://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields.

And it would also help to explain the meaning (or implication) at http://www.django-rest-framework.org/api-guide/relations/#manytomanyfields-with-a-through-model
Is the implication that any m2m models in a serialized object will not be written to the instance during update or create (that's not actually what I see in the source code.  In the source code I see code for m2m in the create method but not the update method).  It would help if the documentation was clear about all this.

**Comment by tomchristie** [comment]
I'll reopen this for us to make a couple of tweaks.

TODO:

* Add a note in [ModelSerializer.update](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L819-824) noting that we don't need to handle m2m attributes separately as we do in `create()`, because the instance already exists.
* Slightly improve the wording in both the "specfiying read only fields" and the "read_only" argument to note that read only fields are present in output representations but should not be present in the input data. read_only fields are not included when creating or updating instances, will be ignored if provided, and do not appear in the serializer.validated_data.

> Is the implication that any m2m models in a serialized object will not be written to the instance during update or create

That's worth re-reading. It's only m2m with a *through* relationship that are set to `read_only` by default. Those `read_only=True` fields are never included, and are not passed through to the `validated_data` argument of the `create()` or `update` methods.

**Comment by xordoquy** [comment]
@nmgeek thanks for the clarifying things. Indeed this part of the documentation can be improved.
