### ISSUE TITLE
Retrieve objects by hyperlink (HyperlinkModelSerializer)

### ISSUE THREAD

**Issue by Mostey** [tomchristie/django-rest-framework#3078]
I have a `DietPlanViewSet` representing a `DietPlan` that can be shared among `Account` objects:

```
class DietPlanSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = DietPlan

class DietPlanViewSet(ViewSetBase):
    queryset = DietPlan.objects.all()
    serializer_class = DietPlanSerializer

    @detail_route(methods=['patch'])
    def share(self, request, pk):
        dietplan = self.get_object()


class DietPlan(models.Model):
    ...
    shared_with = models.ManyToManyField(Account, related_name='public_dietplans')
    ...
```

I want the share function to receive an account (or list of accounts) that should be added to the `dietplan.shared_with` field which is a ManyToMany relation between `DietPlan` and `Account`.

The PATCH request is as follows:

       response = self.client.patch('/dietplans/1/share/', {
                "account": "/accounts/1/"    
        })

But unfortunately I don't know how to let the framework deserialize the `Account` object based on that hyperlink. Well I could get my hands on some RegEx but I think this is not the correct way to achieve what I want.

I also tried to deserialize that request using the corresponding `AccountSerializer` but that didn't work either:

`target_account = AccountSerializer(data=request.data['account'],partial=True)`

May you please help me on this one?

**Comment by carltongibson** [comment]
Hi @Mostey 

First off: ideally you'd use the [Mailing List](https://groups.google.com/forum/#!forum/django-filter) for usage questions and discussions. 

However...

If you send a list of the full hyperlinks to your `DietPlanSerializer` backed endpoint under the `shared_with` key, you should find it just sets the related set as per the docs for [HyperlinkedRelatedField](http://www.django-rest-framework.org/api-guide/relations/#hyperlinkedrelatedfield).

The trick here is that you want to __add__ the specified accounts, rather than replacing the whole set. By hand you'd send just a list of IDs (rather than `/accounts/1/`-type fragments, otherwise you have to parse out the id yourself.), fetch the Account objects and `add` them to the diet plan. If you override `perform_update` on your view you can ask the serialiser for it's `data` and perform the save yourself. (The serializer will replace the whole set if you use its `save` method.)

Hopefully that's more than you need to get moving.
