### ISSUE TITLE
Faster deserialization with cyordereddict

### ISSUE THREAD

**Issue by ze-phyr-us** [tomchristie/django-rest-framework#3109]
I was able to speed up deserialization by 10 - 15% by replacing the stdlib's OrderedDict with https://github.com/shoyer/cyordereddict (Python 3.4, DRF 3.1.1). Is it worth supporting cyordereddict as an optional package? The only change would be in `compat.py`:

```diff
-try:
-    from collections import OrderedDict
-except ImportError:
-    from django.utils.datastructures import SortedDict as OrderedDict
+try:
+    from cyordereddict import OrderedDict
+except ImportError:
+    try:
+        from collections import OrderedDict
+    except ImportError:
+        from django.utils.datastructures import SortedDict as OrderedDict
```

I'm happy to prepare a pull request.

**Comment by tomchristie** [comment]
There's so many potential options for using alternate libraries, configuration for using ordered/unordered dicts etc.etc. that, as usual, I'd rather keep these options farmed out to third party packages to provide.

Noted that this one happens to be a particularly simple change, but I'd still be happier with seeing eg. a comprehensive set of performance improvements all nicely packaged and documented together, rather than have us adopt optional alternate underlying libraries such as this.

**Comment by ze-phyr-us** [comment]
Fair enough. Is there a clean way to apply a change like this in a 3rd party package without having to copy-paste unchanged parts from DRF?

**Comment by hellysmile** [comment]
```Python
INSTALLED_APPS = [
# ...
'your_new_lib',
'rest_framework',
# ...
]
```
your_new_lib -> `__init__.py`
```Python
from cyordereddict import OrderedDict
from rest_framework import  compat

compat.OrderedDict = OrderedDict
```

**Comment by thedrow** [comment]
I was looking for something like this. Thanks!

**Comment by thedrow** [comment]
Also note that this would actually slow down PyPy due to the fact that it uses a CPython extension to speed code up.

**Comment by SalahAdDin** [comment]
:+1:
