### ISSUE TITLE
Singleton resource view set support

### ISSUE THREAD

**Issue by codable** [tomchristie/django-rest-framework#3113]
there are situation where resource is singleton, but there are no appropriate viewset for this situation.

**Comment by thedrow** [comment]
Can you provide an example? This sounds a lot more like a usage question than a feature request.

**Comment by xordoquy** [comment]
Seconded, I don't see any reason a regular `ViewSet` can't represent a singleton resource.
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by claytondaley** [comment]
Singletons are easier to see/understand if you consider nested resources.  The standard example of nesting is to support a one-to-many relationship.  For example, it's common to use a URL like:

`/users/{id}/posts/`

Since a user has multiple posts, the GET method at this endpoint returns a list.  But consider the situation where the two resource are in a one-to-one relationship:

`/account/{id}/profile/`

In this case, it's unnecessary to append an extra `{id}` because the endpoint uniquely identifies the (singleton) profile resource.  If I `GET` at this resource, I expect a detail route.  Similarly, it makes sense to `PUT` (vs `POST`) to this endpoint.  Of course, the `profile` case is equally valid without nesting if the logged-in user uniquely identifies the profile. 

It looks like this would take a relatively modest adjustment to `SimpleRouter.routes` to make it a `SingletonRouter`.  The user will also need to adjust `get_object`, but it's possible to use the existing method if you change `lookup_field` to the `<related>_id` field and inject the `<related>.pk` into `request.data`.  Not sure if there's a better option.

At minimum, this should help the next person who has the same issue.  I'm less clear if it makes sense to add a `SingeletonRouter` since its use requires changes to the view.

**Comment by xordoquy** [comment]
> it's unnecessary to append an extra {id} because the endpoint uniquely identifies the (singleton) profile resource.

I won't get into the specifics but it's no singleton. It's specific to each user which is quite different.

That being said, if you think it's a common use case, feel free to make it a 3rd party.

**Comment by claytondaley** [comment]
> I won't get into the specifics but it's no singleton

The OP describes a "singleton resource" not a singleton object which is OBVIOUSLY different.

**Comment by claytondaley** [comment]
https://github.com/cerebris/jsonapi-resources/wiki/JSONAPI-::-Create-a-Singleton-Resource-Profile

**Comment by rpkilby** [comment]
I'd argue that "singleton resource" isn't really appropriate, given that it somewhat co-opts the original meaning of singleton. I'd probably stick with "single resource endpoint" or something similar.

Regardless, the point is that this is something that can be solved outside of the core framework (at least initially). If the implementation changes are trivial enough and extensively tested, it might be worth re-evaluating if it belongs in the core framework. If not, it's something that would definitely belong on the list of 3rd-party extensions.

**Comment by claytondaley** [comment]
> this is something that can be solved outside of the core framework

Absolutely.  I was dealing with the OP's case, found the issue when looking for existing best practices, and more clearly documented the problem and a solution for the benefit of others who are trying to solve the same problem.  If anyone even bothered to respond (and I didn't necessarily expect it), I would have expected appreciation for clarifying and solving a (historic and potential future) user issue.  

If someone thinks I misunderstood the OP's question, there's no need to condescend about it -- especially a question that is so unclear that the first response is "Can you provide an example".  In the absolutely worst case, I described an unrelated problem and solution that may benefit others.

Of course, the tone is even more upsetting when the OP's term is actually widely/commonly used (no matter your personal feelings on its appropriateness) so my answer is almost certainly a solution to the OP's problem.

**Comment by rpkilby** [comment]
@claytondaley - I simply provided an opinion as to why I think the name is not the most appropriate. I don't know why it came across as condescending, but that was not my intent. 

At this point, it sounds like you have path forward for a potential implementation. If you'd like feedback/input, I'd recommend that the conversation be taken to that repo.
