### ISSUE TITLE
Field level permissions?

### ISSUE THREAD

**Issue by kawing-chiu** [tomchristie/django-rest-framework#3128]
I've read through the doc about permissions but couldn't figure out how to implement field level permission. I have a model like:
```
class Task(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    owner = models.ForeignKey('auth.User')
    status = models.CharField(max_length=2, choices=STATUS_CHOICES)
```
What I'm trying to achieve is: administrator users should be able to modify all fields of the model while normal users can only modify the `status` field. How should this be done?

**Comment by carltongibson** [comment]
First off, please use the [Mailing List](https://groups.google.com/forum/#!forum/django-filter) for usage questions and discussions. Thanks!

(I'd be inclined to override `get_serializer` to restrict the exposed fields, since object level permissions are simple enough but field level would require you to think something through yourself.)

(Unless anyone can point to an out of the box solution...)
