### ISSUE TITLE
can you support  JsonbField ? postgresql

### ISSUE THREAD

**Issue by iloveyo123u1** [tomchristie/django-rest-framework#3141]
can you support  JsonbField ? postgresql

thank you very much

:)

**Comment by carltongibson** [comment]
This isn't really actionable as it stands. As and when Django adds support for Postgres' JSON features we'll certainly look at adding support, just as we did for HStore, Array and other fields with Django 1.8

Otherwise (for the now) you'll need to use Google to explore the various third party takes on this. I'm not currently aware of a first class implementation that you can just plug into Django REST Framework, so you may need to do some work yourself.

**Comment by xordoquy** [comment]
Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
