### ISSUE TITLE
Browsable API View + ModelSerializer returns `{ "my_email_field" : "False" }` via serializer.data

### ISSUE THREAD

**Issue by catskul** [tomchristie/django-rest-framework#3177]
Posting to an endpoint with a ModelSerializer with a single EmailField results in a response with

{ "my_email_field" : "False" }

**Comment by tomchristie** [comment]
Hi @catskul - I'd accept an example of a failing test case, but as this stands I think this needs more digging into from your side before I'd treat this as something requiring investigation.

Try to reduce this to the *simplest possible failing case*, then demonstrate that in a way that makes it clear that there's an issue that we need to look into rather than an unrelated problem in your web application.

More than happy to help if we do have an issue, but don't want to spend time digging into something when it's unclear if it's actually an unrelated problem on your side.

**Comment by tomchristie** [comment]
Note: This wouldn't necessarily need to be a fully fledged pull request with failing test - just enough work to demonstrate that you've fully looked into this and reduced this to the core of any problem.
