### ISSUE TITLE
drf-nested-routers and exception-handling

### ISSUE THREAD

**Issue by gnimmelf** [tomchristie/django-rest-framework#3205]
Hi,

I have this issue open on drf-nested-routers:
https://github.com/alanjds/drf-nested-routers/issues/45

Basically, exceptions in a `NestedSimpleRouter` is not picked up by the `rest_framework.views.exception_handler`, and so neither by any custom exception-handler either.

I think the problem is with `drf-nested-routers`, but creator @alanjds does not think so. This issue is a bit above my level, so I thought I'd see if anyone here can point me in the right direction.

Cheers!

**Comment by tomchristie** [comment]
This is a usage question rather than a bug, so I'm rather limited in how much time I'm able to put into this.
Typically better to ask these on the discussion group instead, as we reserve the issue track for bugs feature work and other ongoing work on the core project itself.

> Basically, exceptions in a NestedSimpleRouter is not picked up

I'm not 100% sure what this means. If NestedSimpleRouter is raising an exception during setup eg while registering a viewset etc... then no REST framework's exception handler won't ever see that.

Anything raised inside a request-response cycle (eg the `except ObjectDoesNotExist` in your example) *will* be caught by the exception handler, and you can customize that.

I'd suggest starting by overriding the (private API) `handle_exception` method on the ViewSet (see https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L411) and verifying to yourself that the exception really is being handled at that level, then move on to implementing a custom exception handler and validate that the exception's being caught there.

If you're still having issues post where you've gotten to on the discussion group and link to it from here, will see what we can do to help.

Cheers :smile:

**Comment by gnimmelf** [comment]
Next time I'll restart the dev-server properly. Suddenly it all worked as intended.

Thanks for your patience w/ me.

**Comment by tomchristie** [comment]
fab!
