### ISSUE TITLE
Django Rest Framework Viewsets / Database Locks

### ISSUE THREAD

**Issue by psychok7** [tomchristie/django-rest-framework#3213]
Hi there so i am using `Django Rest Framework 3.1` and i was wondering if its possible to "protect" my viewsets / database against writes in a per user basis?

In other words if 1 user is saving something the other one cannot save and it either waits till the first user finishes or returns some kind of error.

I tried looking for this answer but couldn't find it.

Is this behavior already implemented? if not how can i achieve this in practice?

cheers

**Comment by tomchristie** [comment]
> In other words if 1 user is saving something the other one cannot save and it either waits till the first user finishes or returns some kind of error.

Do you mean a database transaction around the request, or do you mean acquiring a lock and then working on an instance and eventually saving and releasing the lock?

**Comment by psychok7** [comment]
@tomchristie i mean acquiring a lock and then working on an instance and eventually saving and releasing the lock. And if yes what would happen to the second user? wait till the first one has finished or receive an error?

**Comment by tomchristie** [comment]
No there's nothing built-in for that - it's too specific a use-case, and not a particularly common style.
You'll be best off looking for general patterns for this on stack overflow or similar (tho I'd suggest you phrase the question as on of RESTful web APIs generally, rather than REST framework specfically)

Alternatively try the discussion group: https://groups.google.com/forum/#!forum/django-rest-framework

It's an awkward pattern because what do you do if user 1 drops off the face of the earth? Are locks time expired?

One possibly useful point: 409 Conflict may be an appropriate response when user 2 attempts to edit a resource that is currently locked.

Going to close the issue off as a usage question rather than an actionable bug or accepted feature request - sorry not to have been more help.
