### ISSUE TITLE
Include list_route method in DRF Browsable API

### ISSUE THREAD

**Issue by stephenHartzell** [tomchristie/django-rest-framework#3266]
I'm going crazy trying to figure out how to get the browsable API to show a @list_route custom method on a ModelViewSet. It looks like it should automatically show up in the browsable API but it doesn't. Is this a bug? This unanswered stack overflow question exactly details the issue I'm trying to sort out.

http://stackoverflow.com/questions/30059795/include-list-route-methods-in-django-rest-frameworks-api-root

-Thanks, Stephen

**Comment by tomchristie** [comment]
The default API root view doesn't cover that case.
I'd suggest using SimpleRouter instead of DefaultRouter, and writing the root view yourself (since it's a trivial view which just returns a dictionary of hyperlinks in response to GET requests)

It's possible that we'd consider a pull request adding this functionality, but havn't reached any decision on that and it'd depend on how complex it was.
