### ISSUE TITLE
BooleanField with default=True, is being set to False

### ISSUE THREAD

**Issue by itspage** [tomchristie/django-rest-framework#3302]
I have the following model field
```
    active = models.BooleanField(default=True)
```

For a POST, when this field is missing, the instance used to be created with active = True (as per the default). The instance is now getting created with active = False.

This is occurring since upgrading from 3.1.3 to 3.2.2.

I have to manually declare the serializer field on the model serializer to get it to default to True.

**Comment by tomchristie** [comment]
I assume you're submitting multipart/urlencoded data here (rather than, say, JSON)

This'll be the effect of us fixing a bug: https://github.com/tomchristie/django-rest-framework/issues/2776

HTML checkboxes do not send *any* value when left blank, so for boolean inputs there's no way for us to distinguish between 'not present' and 'false'. If you need to omit boolean values you'll need to submit JSON instead.

Some docs here. http://www.django-rest-framework.org/api-guide/fields/#booleanfield

Possible this should have been called out more loudly.
