### ISSUE TITLE
Modelfields with null=True are not required in serializer  

### ISSUE THREAD

**Issue by Wirzi** [tomchristie/django-rest-framework#3492]
Is this a bug?

I have a model:
```
class Things(models.Model):
	name = models.CharField(verbose_name=_("Name"), max_length=200, null=True)
```

And in serializer I have to write:
```
class ThingsSerializer(serializers.ModelSerializer):
	name = serializers.CharField(max_length=200)

	class Meta:
		model = Things
		fields = ('name',)
```
to make the 'name' field required=True.

Update: 
To have fields required=True with null=True in models is important because of this reason: https://docs.djangoproject.com/en/1.8/topics/migrations/#postgresql

**Comment by tomchristie** [comment]
> Is this a bug?

Nothing there to make me think that shouldn't be expected behavior no.

> To have fields required=True with null=True in models is important because of this reason

Outside the scope of this project, but you might consider performing the following for adding a new column.

1. Add the new column with null=True.
2. Add a data migration to update rows to correct value (probably the empty string)
3. Remove the null=True

It's rarely a good idea to have char fields with null=True, so if you're doing so due to migration reasons you may well want to treat it as a temporary state.

**Comment by Wirzi** [comment]
Ok thanks i will do that.
