### ISSUE TITLE
APIException not returning response on detail_route PATCH

### ISSUE THREAD

**Issue by neilp9** [tomchristie/django-rest-framework#3518]
I have a detail_route (defined in a mixin class) that is throwing rest_framework.exceptions.ValidationError based on the input. When the client sends request as PATCH and the error fires, the response comes back empty. When I send with POST, the Validation error message gets returned in the response, but as a list (['my error message']) rather than a dict key'd with detail.

Why is no response coming back on PATCH? In either case, why isn't the normally formatted response coming back ({ "detail" : "my error message"})

**Comment by xordoquy** [comment]
@neilp9 a test case would help here.

**Comment by tomchristie** [comment]
I don't think this ticket yet meets the criteria for a sufficiently isolated example case. Reduce this to the simplest possible reproducible case, ideally isolating it to demonstrate *just* the serializer behavior, rather than the view as a whole.

As it stands it's not clear if its a valid issue or a usage problem.
