### ISSUE TITLE
When I upgrade to 3.3.0, PAGINATE_BY_PARAM settings does not work.

### ISSUE THREAD

**Issue by Windfarer** [tomchristie/django-rest-framework#3586]
I set 

```
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 18,
    'PAGINATE_BY_PARAM': 'page_size',
    'MAX_PAGE_SIZE': 50,
}
```
in my settings，and it works well in the version of 3.2.5 or before.  
But when I upgrade my restframework to version 3.3.0, I can't specify the num of results by setting the  page_size parameter in url.  

Is there anything about pagination changed in 3.3.0？

**Comment by tomchristie** [comment]
This has been on the standard deprecation path, since 3.1.
You will (or should have) been seeing loud deprecation warning for this since 3.2.

See release notes for 3.1: http://www.django-rest-framework.org/topics/3.1-announcement/
3.2: http://www.django-rest-framework.org/topics/3.2-announcement/#deprecations
and 3.3: http://www.django-rest-framework.org/topics/3.3-announcement/#deprecations

**Comment by Windfarer** [comment]
Thanks, I did miss that. Is there any possible to show deprecation warning when it runs in debug mode as django does?

**Comment by tomchristie** [comment]
Raise an issue with any pointers to Django docs etc and we could consider if there's anything we're currently missing. :smile:  (Not obj to me that we're *actually* doing anything different to Django tho)
