### ISSUE TITLE
upgrading from 3.3.0 to 3.3.1 causes error: FieldDoesNotExist: <Model> has no field named u'id'

### ISSUE THREAD

**Issue by beaugunderson** [tomchristie/django-rest-framework#3674]
I believe it may be related to #3593.

[See here](https://github.com/PersonalGenomesOrg/open-humans/blob/eb5a56af81209350398e0240aaa51ff0abc82afb/studies/american_gut/models.py#L53) for a model that causes this error when serialized.

I think the issue affects models that have a primary key that's not called `id`. (In this model `value` is the primary key).

**Comment by xordoquy** [comment]
Not directly linked though similar. #3593 was for related field while you have the issue on the main model.

**Comment by beaugunderson** [comment]
Here's the smallest possible test case, it works in 3.3.0 and fails in 3.3.1:

```python
from django.conf import settings

if not settings.configured:
    settings.configure(
        MIGRATION_MODULES={'__main__': 'migrations'},
        INSTALLED_APPS=('__main__',))

from django.apps import apps

apps.populate(settings.INSTALLED_APPS)

from django.db import models
from rest_framework import serializers


class TestParentModel(models.Model):
    title = models.CharField(max_length=64)


class TestChildModel(models.Model):
    parent = models.ForeignKey(TestParentModel, related_name='children')
    value = models.CharField(primary_key=True, max_length=64)


class TestChildModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = TestChildModel
        fields = ('value',)


class TestParentModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = TestParentModel
        fields = ('id', 'title', 'children')

parent = TestParentModel(title='abc')
child = TestChildModel(value='def', parent=parent)

serializer = TestParentModelSerializer(parent)

print serializer.data
```

**Comment by benred42** [comment]
So, I did a little digging around on this issue using the test case posted above and here's what I found:

The issue does appear to be coming from the change made in #3593 in ``serializers.py``. It looks like what is happening is when ``relation_info.related_model._meta.get_field(to_field).primary_key`` gets run in ``build_relational_field()``, the ``to_field`` it is using is actually the pk for the TestParentModel, not the child.  This happens because when ``_get_reverse_relationships()`` in ``model_meta.py`` tries to resolve the ``to_field`` it uses the field from the ForeignKeyObject for the forward relationship, not the related object, so it ends up using its own pk instead of TestChildModel's.

Sorry if that is really confusing.  Tracing all those relationships has left me somewhat incoherent.  I'll put up a PR with a fix that solves the issue and maybe that will make things a bit clearer, although I'm not convinced it is the best/right fix.

**Comment by beaugunderson** [comment]
Thanks for digging into this @benred42! Happy to test your PR in my environment when it's ready. :)

**Comment by beaugunderson** [comment]
Noting that #3696 does fix the errors in my environment.

**Comment by tomchristie** [comment]
@beaugunderson Okay, good to know. If we can replicate in a test case then we're good to go!

**Comment by beaugunderson** [comment]
It looks like this has a good PR that includes a good test case now: #3852. :)
