### ISSUE TITLE
Read-only fields fail silently on KeyError and AttributeError

### ISSUE THREAD

**Issue by umutbozkurt** [tomchristie/django-rest-framework#3738]
Any serializer field with `read_only=True`, do not raise exception on properties.
I think this is not intended behavior and it's caused by [this](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L462-L465) and [this](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L404-L408).

Failing test case:
```Python
def test_property_exceptions_during_serialization(self):
        class ExampleSerializer(serializers.Serializer):
            key_error = serializers.CharField(read_only=True)
            attr_error = serializers.ReadOnlyField()

        class PropertyExceptions:
            @property
            def key_error(self):
                raise KeyError()

            @property
            def attr_error(self):
                raise AttributeError()

        instance = PropertyExceptions()
        serializer = ExampleSerializer(instance)

        with pytest.raises(ValueError):
            serializer.data
```

Probable solution:
Changing [fields.py L:76-82](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L76-L82) as following:
```Python
        try:
            if isinstance(instance, collections.Mapping):
                instance = instance[attr]
            else:
                instance = getattr(instance, attr)
        except ObjectDoesNotExist:
            return None
        except (KeyError, AttributeError):
            raise ValueError()  # same as callable
```

**Comment by dimitrovskif** [comment]
Why aren't you using `SerializerMethodField`?

**Comment by umutbozkurt** [comment]
I am trying to serialize a model property. I don't need a method field since it can be done automatically with field *source*. And I am faking a model property because it is a test case.

**Comment by tomchristie** [comment]
I think we just need to accept that properties that raise `KeyError` or `AttributeError` are going to be treated the same as a nonexistent property, and treat it as an inherent limitation.

I don't see any other resolution to this.

**Comment by jslang** [comment]
What was wrong with the proposal made by @umutbozkurt?

> I think we just need to accept that properties that raise KeyError or AttributeError are going to be treated the same as a nonexistent property

This is problematic. It hides legitimate exceptions raised during the course of property evaluation.

**Comment by xordoquy** [comment]
> What was wrong with the proposal made by @umutbozkurt?

The change may have side effects - what if instance has no key or attribute attire ?
Properties should not raise `KeyError` or `AttributeError`. Those are not legitimate exceptions. If an error occurs, the property should raise a proper - often defined on purpose - exception.
For example, Django does not raise a default Python exception when a query set's get fails. It raises an ObjectNotFound.

**Comment by jslang** [comment]
I understand your issue with the proposed solution.

> Those are not legitimate exceptions. If an error occurs, the property should raise a proper - often defined on purpose - exception.

Perhaps I misspoke, what I meant by legitimate exception is something unexpected. A bug in the evaluation of the property. Short of wrapping the property in a try...catch, there is no way to raise defined errors for unexpected things like that. Had this happen recently and the behavior here hid the fact that it was happening. My garbage code was throwing an `AttributeError`, and the catching of that exception in DRF for the purpose of evaluating whether or not it existed was hiding that error.

The problem is that the property does exist, but it errors during the course of evaluation. If that error is a `KeyError` or an `AttributeError` the exception is swallowed and nobody is made aware of it.

What I'm wondering is if there is a way to allow such exceptions to propagate while maintaining the existing behavior.

> If an error occurs, the property should raise a proper - often defined on purpose - exception.

Yes, and I believe DRF might be able to do something like that in this case:

```python
def get_attribute(instance, attrs):
       ....
        try:
            if isinstance(instance, collections.Mapping) and attr in instance:
                instance = instance[attr]
            elif attr in dir(instance):
                instance = getattr(instance, attr)
            raise InstanceAttributeNotFound('Instance has no key or attribute %s' % attr)
        except ObjectDoesNotExist:
            return None
```

And then instead of catching `AttributeError` or `KeyError`, DRF can catch `InstanceAttributeNotFound` or something else with a better name 😄 .

Main goal is to avoid swallowing any exceptions the property may throw during evaluation.

**Comment by xordoquy** [comment]
Provided that Python's `hasattr` does also "hide" the `AttributeError`, I'm going to consider this is an expected behavior from the language itself.

    >>> p = PropertyExceptions()
    >>> p.attr_error
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "<stdin>", line 7, in attr_error
    AttributeError
    >>> hasattr(p, 'attr_error')
    False
    >>> 

I need to think a bit more about the `KeyError` case.
