### ISSUE TITLE
Why documentation is so unclear?

### ISSUE THREAD

**Issue by lectricas** [tomchristie/django-rest-framework#3744]
I'm new in django(and they have a good doc with tutorials)  but I cant understand a thing in yours! It is not clear for newbie what should be done!

**Comment by xordoquy** [comment]
@lectricas I'm sorry you have hard time with the tutorial. I've got a lot of good feedback about it. Could you be more precise about what are the hard parts ?
Unless we have something more specific there's no way we can improve it.

**Comment by lectricas** [comment]
Cant find a way to implement token authentication. My goal is to log into the django via android app. For that purpose I suppose i need REST thing. I've done that but from android side having just functions like "sitename.con/user/authenticatie" and send him a post method with my credentials. I cant find a thing "weather this is suitable for that" and how I can make this "sitename.con/user/authenticatie" function.

**Comment by xordoquy** [comment]
We do have a [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) which is the best place for usage questions.
I'm closing this because the scope is too wide to be processed within an issue and -according to me- [the documentation already explains token authentication](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication).

**Comment by tomchristie** [comment]
Seconded was also about to close this as unproductive.
Doesn't mean we're not interested in helping, but the ticket tracker is for clear, identifiable work or bugs.
