### ISSUE TITLE
django-rest-framework-json-api

### ISSUE THREAD

**Issue by jerel** [tomchristie/django-rest-framework#3807]
We have a third party package to implement [most of] the jsonapi.org specification at https://github.com/django-json-api/django-rest-framework-json-api It's at 2.0.0 beta currently and I wondered if it would be useful to list it in the DRF docs?

**Comment by tomchristie** [comment]
Absolutely yes please!
I'd suggest putting it in the parsers and renderers sections right?
Also make sure to add it to the REST framework grid of Django packages: https://www.djangopackages.com/grids/g/django-rest-framework/

Finally if you post something on the discussion group, and also possibly tweet it cc'ing me so that I can RT.

Nice work!
