### ISSUE TITLE
Validate pagination (max page).

### ISSUE THREAD

**Issue by birdonfire** [tomchristie/django-rest-framework#3920]
If I have a result set containing 5 items and a page size of 10, then there's only 1 actual page of results. If you request page 2, they get back a 200 response with an empty result set. If you request page 600, you get back a 200 response with an empty result set (and previous page URL is set to page 599). 

This is pretty forgiving behavior, and I think it's okay as a default or option. However, it would be nice to have the option (built-in) to instead respond with a 400 bad request and indicate that the requested page of results does not exist.

**Comment by Curious72** [comment]
@birdonfire Can i take this up ? Can you point me towards the files which must be changed?

**Comment by tomchristie** [comment]
Seems reasonable, yes.
I'm happy with either 2xx or 4xx, but def willing to consider PRs here.
Relevant area in the codebase is here: https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/pagination.py#L205-L211

**Comment by arijeetmkh** [comment]
@tomchristie The paginator that you referred to as the relevant area in the codebase (PageNumberPagination), seems to already handle the 'django.core.paginator.InvalidPage' exception which is a super class of both 'PageNotAnInteger' as well as 'EmptyPage'. Which means querying for a valid but out of range page number already gives a 404 error.

The only thing I can think of changing is, instead of returning the generic 'rest_framework.pagination.PageNumberPagination.invalid_page_message', we could return a different message in case the page number was valid (ie was of int type) but was out of range.

**Comment by tomchristie** [comment]
> querying for a valid but out of range page number already gives a 404 error.

In which case I don't see anything that needs doing here.
