### ISSUE TITLE
Adding views, not only viewsets to Browsable API via routers

### ISSUE THREAD

**Issue by BurkovBA** [tomchristie/django-rest-framework#3931]
It is often desirable to be able to add views, not viewsets, to the Browsable API. For instance, see: http://stackoverflow.com/questions/18818179/routing-api-views-in-django-rest-framework.

There are custom router solutions, such as [this outdated HybridRouter implementation on stackoverflow](http://stackoverflow.com/questions/18817988/using-django-rest-frameworks-browsable-api-with-apiviews), but it would be nice to have this functionality out-of-the-box and consistent with evolution of DRF

**Comment by tomchristie** [comment]
Closing given lack of interest. We may reconsider if this is subsequently raised by other developers. Not sure I see the value over simply adding views explicitly to the URL conf.

**Comment by browze** [comment]
It seems to me that the value is that it would add those urls to the 'browsable' api?  Having just tried it and cast around on SO, it appears to me that something in the vein of the solution shown by BurkovBA above (or some other significant customisation) is still necessary in order to include certain 'single' views in the browsable API - for example a url that returns a single detail view and which doesn't require any kind of id to be passed (e.g. because its an aggregate view, or alias for a particular instance (e.g. '/me'), or a singleton model).  Apologies if I'm missing something obvious.  Assuming that is so, the lack of support does seem (to me) to hamper creating a self describing API.  Thanks for DRF btw @tomchristie - it's great!

**Comment by xordoquy** [comment]
It feels quite complex to me while writing the same view as a `ViewSet` gets you the integration for free.
Don't forget that you can pick the desired behaviour for a `ViewSet` by implementing only a subset of the methods. For exemple, only implementing `list` or inheriting from `ListModelMixin` will not show details or creation for that `ViewSet`.

**Comment by BurkovBA** [comment]
@xordoquy True, but pure views (especially function-based) give you much more flexibility. E.g. you want to add api schema view to the browsable api, what do you do?

**Comment by browze** [comment]
On revisiting today, I quickly realised actually I don't have to customise to avoid passing an id if I set (or leave) detail as false on the @action decorator.  Last night I was a bit whacked and I guess I had wrongly assumed that if I didn't set detail = True it would only allow the result to be passed back as an array.  Thought I'd mention this for anyone else as dozy, happening on this thread.  

I don't know whether or not leaving detail = False is broadly inline with the 'idea' behind the flag when I'm presenting a view that isn't a collection of anything - however even it wasn't quite, that's probably quibbling...  For me this helps and would address many of my use cases even if occasionally I had to create an otherwise unnecessary viewset and I do get that it might keep the internals simpler..

However obviously there may be some cases (such as the api schema one just cited by @BurkovBA) where it might be necessary/really helpful to be able to install things that aren't viewset @action s at all and/or have them registered at root, - so just FWIW personally I still think it might be great to have that supported :)

**Comment by Reubentrapdoor** [comment]
I would like to add my token auth endpoint to the API browser so my users actually know where to find it, but since ObtainAuthToken inherits from APIView I can't find a good way to do that.

Am i supposed to just reimplement that whole thing as a viewset then just to be able to use DefaultRouter and get the URL to show up?

**Comment by rpkilby** [comment]
It's not an ideal solution, but you should be able to create a viewset that inherits `ObtainAuthToken`, then point `create` to `post` something like..

```python
class AuthTokenViewSet(ObtainAuthToken, ViewSet):
    def create(self, request, *args, **kwargs):
        # note that we need to call super here, so that we call `ObtainAuthToken.post`
        # instead of the `post` method set by `ViewSet.as_view()`
        return super().post(request, *args, **kwargs)
```

Let me know if that does/doesn't work.

**Comment by Reubentrapdoor** [comment]
That sees to work nicely for my use case thanks! Wouldnt have thought to use multiple inheritance myself.

**Comment by carltongibson** [comment]
Or, [subclass `DefaultRouter` and customise the `APIRootView`](https://github.com/encode/django-rest-framework/blob/37dcd553705421201f00fb7f6a75a6214afb9d60/rest_framework/routers.py#L341-L350) to explicitly add the auth view, [similar to how we manually define that in the tutorial](https://www.django-rest-framework.org/tutorial/5-relationships-and-hyperlinked-apis/#creating-an-endpoint-for-the-root-of-our-api).

**Comment by eldano1995** [comment]
I too like the idea of adding views to the browseable API using the router.

But this would be solved if there was a way to implement complex  path_url in the action inside a ModelViewSet. 

For example, let's say I have an UserViewSet and that I would like to have two additional endpoints: one for requesting password reset (**users/request_password_reset/**), and the other for  actually resetting the password (**users/reset_password/<uidb64>/<token>/**). The fields uidb64 and token are used to confirm that the user clicked the reset_password_link that was sent to his/her email.

The previous is a common use case scenario. You could argue that given your are doing a POST request to **users/reset_password/<uidb64>/<token>/**, you could simplify the url to **users/reset_password/** and send uidb64 and token as POST params. But in a similar case, where you wouldn't use POST, like in **users/activate_account/<uidb64>/<token>/** (GET request), that wouldn't be possible.

That's why I think it would be great to allow to enable complex url_path in the action decorator function.

**Comment by auvipy** [comment]
> Closing given lack of interest. We may reconsider if this is subsequently raised by other developers. Not sure I see the value over simply adding views explicitly to the URL conf.

this could be moved to the discussion section
