### ISSUE TITLE
Enhancement proposal: allow accessing the request in filters

### ISSUE THREAD

**Issue by dvarrazzo** [tomchristie/django-rest-framework#3977]
Filter objects currently don't allow accessing the request. This can be useful to find objects which are in a certain relation with the user accessing the request. I worked around it with a simple subclass of `DjangoFilterBackend`:

```python
class MyFilterBackend(DjangoFilterBackend):
    def filter_queryset(self, request, queryset, view):
        cls = self.get_filter_class(view, queryset)

        if cls:
            f = cls(request.query_params, queryset=queryset)
            f.request = request
            return f.qs

        return queryset
```

After which the request user can be accessed:

```python
class Filter(filters.FilterSet):
    relation = django_filters.MethodFilter(action='filter_relation')

    def filter_relation(self, queryset, value):
        user = self.request.user
        return queryset.filter(id__in=some_search_involving(user, value))
```

Would it be worth adding this simple feature to the framework?

**Comment by tomchristie** [comment]
Right now I'd like to leave this for use-code to deal with. It's not certain that `DjangoFilterBackend` won't become a third-party package, and I'm not super-keen on modifying it at this point in time.

**Comment by sassanh** [comment]
I guess whether it ends up in a third party package or not, DRF needs to have a similar mechanism like `serializer_context` for `filterset`s. Something like `get_filterset_context` which provides information required for filtersets and is provided passed to them.

**Comment by sassanh** [comment]
Currently there's no clean way to provide `request` to filters. The above solution is not considered clean as `filter_queryset` method may change in a new version if DRF in a manner that is not compatible with above code, it's overriding it and doing what it does instead of calling `super(X, self).filter_queryset(...)` which is right way to override methods in libraries to make sure it'll stay compatible in future releases but currently it's not possible as `filter_queryset` returns queryset, not the filterset.

**Comment by kevin-brown** [comment]
Right now our hack for getting around this is to pass in the user (which is the only thing we care about on requests) in through the query parameters which are passed into filters. This required us to create a custom mixin which we add to the `DjangoFilterBackend` so we can access it in our custom FilterSet classes. In our `__init__` methods we fish out the user which is passed in and change the querysets based on it.

It's slightly better than replacing the full `filter_queryset` method, because we can just call `super`, but slightly worse because we can't guarantee that the user/request is going to be passed into the filterset at all times.

**Comment by sassanh** [comment]
@kevin-brown well I really hope this feature gets implemented in the core so that you can get rid of that mess.

**Comment by rpkilby** [comment]
btw - the backend code has been migrated to django-filter (see #3371). Issues should be opened in django-filter's repo.

**Comment by rpkilby** [comment]
See carltongibson/django-filter#494

**Comment by carltongibson** [comment]
Something in this realm will make it into Django Filter for the upcoming 1.0. 

My preference is to give the filter(set) a reference to the request. If there are use-cases that wouldn't cover pleas make some noise on the Django Filter repo.
