### ISSUE TITLE
Redirect on DELETE when using AdminRenderer

### ISSUE THREAD

**Issue by jpadilla** [tomchristie/django-rest-framework#4127]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Following up on #4106 for an improvement

![](https://cloud.githubusercontent.com/assets/83319/15278229/7db384e6-1ae3-11e6-9b5c-6492c6ed80dc.gif)

## Expected behavior

Redirect back to `/users/` after DELETE.

## Actual behavior

URL is still set to `/users/:id/`

**Comment by rocktavious** [comment]
+1 I have experienced this, i got around it by hacking the ajaxform.js script that's used, but would love for a framework supported solution/fix.

**Comment by carltongibson** [comment]
This is related to something I was thinking about before the Kickstarter campaign (but haven't had time to ponder since)... — it would be nice if we could use a DRF backend to serve various versions of a site/API. 

We can do that to an extent but sometimes (like here) you need a slightly different behaviour — based on the accepted renderer. For pure JavaScript Apps you can serve a single page and then eat the JSON but there a _regular_ HTML driven webpage needs something like Vanilla Views' `form_valid` hook — which can somehow proxy to the renderer — to specify the `next` — to use a term — behaviour. 

(Obviously the renderer is a bad place for this kind of logic — but it's the sole thing that varies in line with the requirement here.)

I'd like to see something like this. I'm not sure it's simple.

**Comment by tomchristie** [comment]
Resolved via #4106.

**Comment by jpadilla** [comment]
Yay!

**Comment by tomchristie** [comment]
Thanks as ever, @jpadilla!

😄
