### ISSUE TITLE
Allow Overriding Key for Results when Paginating

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#4182]
Right now it is hard coded as `results` (see for example: [this](https://github.com/tomchristie/django-rest-framework/blob/bb22ab8ee7c5d484dde7112dbe5551bcfc89d7d3/rest_framework/pagination.py#L158)). I suggest making this a class prop allowing a user to subclass and change.

This comes up when trying to match JSON-API which expects the name of the key to be `data`.

**Comment by tomchristie** [comment]
I'd suggest overriding `get_paginated_response()` and `get_results()`. (I don't particularly want to make all the key names that are used in `get_paginated_response()` be class attributes, and I'm not particularly keen to introduce extra API for the specific case of `'results'`.) 

I do think it's odd that we define `get_results()` in the base class, rather than using `NotImplemented`, so *that* should probably change.
