### ISSUE TITLE
run_validators does not seem to conform the steps in Django

### ISSUE THREAD

**Issue by laurentsigal** [tomchristie/django-rest-framework#4351]
In Django, the following happens for the validation of a model field:
- value = to_python(value)
- run_validators(value)

[reference](https://github.com/django/django/blob/49b4596cb4744e4b68d56e6a540a3e15c1582963/django/db/models/fields/__init__.py#L591)

In my case, to_python is transforming from a JSON string to a dict.

Therefore the validators are not consistent depending whether it is called at the serializer level (via serializer.is_valid) or at the model level (via model.full_clean for instance).

I would love to know if there is a good way to reconcile.

Sorry if this is not the best place to post this question, but this seems like a "bug" to me, in that it does not allow to use validators how they were designed in plain Django

**Comment by tomchristie** [comment]
Yes there's a slightly different approach to the design there. The Serializer/ModelSerializer classes are designed several years after Django's Form/ModelForm, and we've been able to address what I believe to be awkward design issues with the original take.

Model validation means that you have to instantiate (but not persist to the DB) a model instance. That's awkward, because eg any Many to Many relationships cannot be populated until the model has been persisted, so you have this weird state of validating a partially-complete model instance, and then filling in the remaining values when the instance is persisted.

The design in REST framework is cleaner because the validation is entirely the responsibility of the serializer. This means it's easy to switch between a ModelSerializer class and an exactly equivelent Serializer class, which is not true of ModelForm and Form.

There's some more in depth discussion of this in my Django Under the Hood talk, here:

https://www.youtube.com/watch?v=3cSsbe-tA0E

> I would love to know if there is a good way to reconcile.

Ensure that your user-facing validation is performed at the serializer level.
If you want to have hard-fail consistency rules by all means do that at the model level, but any input that's intended to raise a validation error and be reported to the user should occur before prior to instantiating & persisting the model instance.

There's also a few places on the discussion group and issue tracker where this has been raised/discussed, so worth searching around for.

**Comment by laurentsigal** [comment]
Thanks a lot for the answer!
