### ISSUE TITLE
blank vs. null

### ISSUE THREAD

**Issue by claytondaley** [tomchristie/django-rest-framework#4353]
If we want to be consistent with the semantics of Model, I believe we need to remove `null` from the exclusion criteria [here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/field_mapping.py#L100):

 - [blank](https://docs.djangoproject.com/en/1.9/ref/models/fields/#blank) applies to inputs, indicating whether or not their optional
 - [null](https://docs.djangoproject.com/en/1.9/ref/models/fields/#null) applies to databases, indicating how a blank value is stored (empty string vs. true database `NULL`)

Since `required` is an input rule, `blank` (and `default`) but not `null` are the appropriate flags to consider.

**Comment by xordoquy** [comment]
`null` also applies to API as input rule which is different from forms.

    {'name': None}

is a different intent from:

    {'name': ''}

It is independent from a database contraint since it also applies to non model objects.

**Comment by tomchristie** [comment]
If a model has null=True you're able to instantiate it without passing that field, and it'll end up being assigned `None`. It's returned by `Field.get_default()`.

(Note the `default` isn't strictly an "input rule" either, but it's still applied)

**Comment by claytondaley** [comment]
@xordoquy agreed, but that distinction is handled [here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/field_mapping.py#L103) (the next block of code).

@tomchristie according to all of the documentation on Model, you should include both `blank=True` and `null=True` to get the behavior you specify.  `blank` says "you may exclude it" and `null` says "and the excluded value is null not empty string".  Traditionally `null=True and blank=False` is an incoherent setting because you never reach the `null` behavior.  DRF handles this combination differently.

**Comment by tomchristie** [comment]
Personally I think the current behavior is intuitively what I'd expect to see.
HTML forms can't represent null, whereas Serializers can, so I don't think the "blank=True should *also* be used" really holds up.
Not really minded to alter it, can't see either the value in doing so, or it being more obvious behavior, plus it'd represent a huge backwards breaking change.

**Comment by claytondaley** [comment]
I agree that Django's default behavior is counter-intuitive.  In fact, that's why I'm so confident of it.  Every time I switch back to Django, I try do to the intuitive thing, it doesn't work, and I have to fix it.

However, I view Django's documented behavior a little like the RFC.  You should follow the spec even if it's counter-intuitive.... because there is a real (and significant) benefit to users if ModelForm and ModelSerializer behave in the same way.  Otherwise, anyone using both (or migrating from one to the other) has to troubleshoot a strange edge case that's buried deep inside the serializer... then has to remember to manually patch the `required` flag on all of their serializers.

Since Django's Models are already documented to work this way, I also find the backwards-compatibility argument weak.  Most Django developers already learned this lesson, build models correctly, and will be unaffected.  The few people who don't will benefit from learning the correct way to build Models in Django.

Obviously, my models are right (and unaffected) so I'm not going to belabor the argument.  If you aspire to see this module become `django.rest`, you're going to have to fix it sooner or later... and you minimize the pain the sooner you fix it.

**Comment by kevin-brown** [comment]
I'm going to throw it out there: This change would only need to be made to handle an edge case (`blank=False` and `null=True`), which doesn't actually make sense by Django's logic. Because otherwise it would be optional anyway (`blank=True` and `null=True`) or it would be required, as you'd normally expect (`blank=False` and `null=False`). _Note that the last option, `blank=True` and `null=False`, is handled the same across both Django and DRF._

> Traditionally null=True and blank=False is an incoherent setting because you never reach the null behavior.

Django within forms handles `null` as [allowing for `None` as a valid choice](https://github.com/django/django/blob/5c63b3e5a797102d915e1683971517f747a28013/django/db/models/fields/__init__.py#L855-L856), regardless of whether or not the field is required. You can verify this in the [model validation](https://github.com/django/django/blob/5c63b3e5a797102d915e1683971517f747a28013/django/db/models/fields/__init__.py#L579-L580), which only checks for `null=False` and `None` being passed. DRF does _exactly_ the same thing for validation, `null` only determines if `None` is a valid value, so that part isn't different.

----

_At best_, you can consider Django Forms to handle a _subset_ of functionality provided by DRF. It only works on form data, which has a very loose concept of `None`, while DRF allows for serializing more than just form data, including some formats which have a rigid and well-defined concept of `None`.

**Comment by raunaqss** [comment]
For what it's worth, I think @tomchristie approach makes sense. 

Serializers can represent None. Also, what if someone wants to use forms for certain HTML views? In this case, using `blank=True` along with `null=True` would mean something different from just setting `null=True` (which does not affect api views).
