### ISSUE TITLE
Consider adding fields for detail/list route + GET + query params to schema generation

### ISSUE THREAD

**Issue by rapilabs** [tomchristie/django-rest-framework#4441]
I have a `ViewSet` `list_route` that is setup for `GET` using query parameters.  The `CoreAPI` schema generator does not include these serializer fields in the schema but I think they should be considered for inclusion (although I'm not entirely sure how one would go about determining that 😊)

I know that `filter_fields` will be included in the schema, however, essentially this `list_route` is more of a RPC action related to the collection, rather than an action that returns a list.

```
class ExampleViewSet(ModelViewSet):
    ...
    @list_route(methods=['get'], serializer_class=SpecificSerializer)
    def specific_list_action(self, request):
        serializer = self.get_serializer(data=request.query_params)
        ...
```

**Comment by tomchristie** [comment]
There's no way we'd be able to automatically determine when we should do this.

However, the `version-3-5` branch now includes plenty of improvements to the schema generation API. We'll be documenting these in order to ensure that they're fully customizable.

**Comment by ramusus** [comment]
Any progress on this feature? I see version 3.6 already released, so is there any way to include fields in the schema for @list_route methods?

**Comment by ramusus** [comment]
@tomchristie I think there is a way to determine which fields are associated to @list_route decorated view. For example, it's possible to define `filter_class` as well as `serializer_class` and take those fields from associated class. But the problem is deeper: @list_route decorated view are not treated as list view in `is_list_view()` method here https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/schemas.py#L137 during schema generation.

**Comment by xordoquy** [comment]
@ramusus feel free to open a PR if you think you can get something working. I'm also considering working on "less obvious" cases for documentation / schema generation though I can't commit to anything.
