### ISSUE TITLE
Improve support for generic relations

### ISSUE THREAD

**Issue by MikiSoft** [tomchristie/django-rest-framework#4447]
http://stackoverflow.com/questions/39191676/drf-serializer-with-generic-foreign-key-check-if-given-object-id-exists-before - it seems that there isn't any "native" way of doing such, and also there isn't any way of accessing the `content_object` in a validator (because `serializer.save()` isn't called, therefore `content_object` has still null value at that point), and I can't do a comparison or a check of that selected object.
Is there a possibility to make doing such things easier?

**Comment by tomchristie** [comment]
There's no simple drop in solutions for GenericRelationships, because of the unbounded nature of the objects and representations that they might be used to refer to.

You'll need to handle any validation with a custom field. There's some documentation along these lines (although more specifically for serialization rather than validation), available here:

http://www.django-rest-framework.org/api-guide/relations/#generic-relationships

This third party package might also be useful:

https://github.com/Ian-Foote/rest-framework-generic-relations
