### ISSUE TITLE
Get actual view instance involved when generating view OPTION and description

### ISSUE THREAD

**Issue by jangsutsr** [tomchristie/django-rest-framework#4457]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Description
It seems that Django REST tacitly assumes help text for a view is classwise, like [here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L237), but in our application we actually need instance-specific attributes (like `SomeView.instance`) to generate accurate OPTION response and view descriptions. It might be worthwhile making it an option.

**Comment by tomchristie** [comment]
Can see that this would be useful in some cases, but for the majority, I think having the view description be constrained as a property of the view itself, rather than a property of the view-for-a-given-instance is reasonable. I'd suggest using a mixin to override the default `get_view_description`, or else a [custom metadata class](http://www.django-rest-framework.org/api-guide/metadata/#custom-metadata-classes) to generate the `OPTIONS` details differently.
