### ISSUE TITLE
Problem serializing a custom many to many related field

### ISSUE THREAD

**Issue by MadWombat** [tomchristie/django-rest-framework#4518]
I have two models related to each other via a ManyToMany field. I defined a ModelSerializer for one of the models and a custom RelatedField for the second model. I defined both to_internal_value() and to_representation() for the custom field and expected the serializer to use it to do read-write operations. I got a ValueError because somewhere along the way the original field name for the ManyToMany field got replaced by lower case version of the model it linked to.

I posted the code and the error in this stackoverflow question. Seems like this is a genuine issue where an important piece of data gets dropped in processing. 
http://stackoverflow.com/questions/39706882/serializing-custom-related-field-in-drf

**Comment by xordoquy** [comment]
We will need a failing test case to help us reproduce and understand your issue.

**Comment by MadWombat** [comment]
I have posted some code to recreate the problem at the stackoverflow question that I linked. I cannot post the actual code I am working on because of legal reasons. I can probably construct an example from scratch to make this problem appear, but that would take some time.

**Comment by MadWombat** [comment]
I have figured out the problem, it seems. In order for the default ModelSerializer create() and update() to work with my custom RelatedField class (pointing to a ManyToMany field). The `to_internal_value()` method in my custom field class needs to save the instance before returning it. I think a note to this effect could be useful in the serializer relationships page, since the serializer fields page actually has an example showing an unsaved instance being returned by that method.

**Comment by xordoquy** [comment]
Could you be more specific about the example you are refering to ?

**Comment by MadWombat** [comment]
OK. In the docs related to making custom serializer fields the docs say that you need to implement `to_internal_value()` to make the field writable and the example returns an unsaved instance `Color(red, green, blue)` http://www.django-rest-framework.org/api-guide/fields/#examples

In the docs about custom relational fields the example doesn't implement `to_internal_value()`, but the docs say the same thing, that you need to implement it to make the serializer read-write http://www.django-rest-framework.org/api-guide/relations/#example_1

It seems that for ManyToMany relations to work with custom RelatedField subclass `to_internal_value()` needs to return a saved instance.

**Comment by tomchristie** [comment]
> the example returns an unsaved instance

Note that the example returns a regular instantiated object, not a model instance.

The issue here is nothing to do with custom fields, but rather to do with the fact that writeable nested serializer relationships need explicitly defined `.create()` and/or `.update()` methods on the parent serializer, in order to fully describe how the various instances should be saved.

More docs on this here: http://www.django-rest-framework.org/api-guide/serializers/#writable-nested-representations

**Comment by MadWombat** [comment]
I am confused. The docs about custom relational fields say "If you want to implement a read-write relational field, you must also implement the .to_internal_value(self, data) method". If I have to implement create() on the parent serializer, why do I have to implement to_internal_value() on the field?

**Comment by tomchristie** [comment]
A custom relational field is not what you need - that's for quite a specific case where you want a different kind of representation than any of the existing relational styles provide for.

You can use a regular nested serializer for the representation described in http://stackoverflow.com/questions/39706882/serializing-custom-related-field-in-drf

Take a look at [Nested Relationships](http://www.django-rest-framework.org/api-guide/relations/#nested-relationships) and Writeable Nested Relationships in particular.

Re-reading through the docs, it's possible that we could do with making the distinction more clear. Very few folks will need custom relational fields.

**Comment by tomchristie** [comment]
I've rejigged the structure slightly, drawn a demarcation between the two sections, and introduced the "custom relational fields" part with a preamble that makes it more clear exactly what they're intended for.

**Comment by MadWombat** [comment]
Thank you for your answers. I hope I am not too much bother, but I am still a bit confused. So, the purpose of subclassing RelatedField is to provide a custom representation for the related object. Which is what I used it for. I could subclass ModelSerializer and use that instead, but since my related objects would never be serialized on their own it seemed like an overkill.

The docs and your answers seem to imply (at least in my understanding), that any serializer that wants to be read-write and contains any relational fields needs to implement its own create() and update(). If that is the case, why does RelatedField implement to_internal_value()? Why would it ever need it? If that is not the case, what am I missing? What would be a use case where a relational field gets de-serialized by the default create() and update() implementations?

**Comment by tomchristie** [comment]
> So, the purpose of subclassing RelatedField is to provide a custom representation for the related object. Which is what I used it for. 

Using a nested serializer is the right approach to the representation you've described. They're specifically designed with this use-case in mind.

> any serializer that wants to be read-write and contains any relational fields needs to implement its own create() and update()

No. *Nested* serializers that want to be writable need to, others do not. There's all sorts of complexities around handling nested updates, that it makes sense to be *explict* about how you want the save to occur, rather than using super-magical behavior.

> If that is the case, why does RelatedField implement to_internal_value()? Why would it ever need it?

Let's say you want to represent a related Person model, with name, role and company attributes, as a literal string, eg: "Tom Christie (Software Engineer, Encode OSS)" - You decide that you also want to be able to update the representations using the same literal strings. In that case you'd need a custom related field that maps between Person <--> String representation. This isn't a typically sort of use case, but you can do so if you want to, and it's also the basis for the various other relational types that we provide.  (Note that it also has nothing to do with the save behavior.)

In most cases tho you'll either want a nested representation, like Person -> {"name": ..., "role", ...}, a pk representation, a hyperlink representation, or a slug relation (Eg if name was a unique field, then just the name string itself as an identifier.
