### ISSUE TITLE
Try to get WWW-Authenticate header from all Authentication Classes

### ISSUE THREAD

**Issue by leonardoarroyo** [tomchristie/django-rest-framework#4680]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Use more than one class in `REST_FRAMEWORK.DEFAULT_AUTHENTICATION_CLASSES`, where the first class does not implement `authenticate_header()`.

## Expected behavior
Drf should try all declared authentication classes to find a valid challenge header.

## Actual behavior
Drf calls only the first object(`return authenticators[0].authenticate_header(request)`)

**Comment by xordoquy** [comment]
What would be the motivation behind that change ?
Wouldn't that leave to some unintentional side effect like what if I explicitly don't want the www-authenticate header ?

**Comment by leonardoarroyo** [comment]
Yeah, that does make sense.
My motivation was that `NotAuthenticatedException` explicitly declares `status_code = status.HTTP_401_UNAUTHORIZED`.

Raising a `NotAuthenticatedException` and getting 403 felt like undocumented behavior, although I now see it's documented [here](http://www.django-rest-framework.org/api-guide/authentication/#unauthorized-and-forbidden-responses).

Although the `401` MUST include the WWW-Authenticate, the RFC says this about the `403` response: `The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated.`. The fix I submitted does not address this.

Should the correct behaviour in this case be to raise an internal server error and let the developer handle it?

**Comment by xordoquy** [comment]
The underlaying issue is that application login such as default Django one isn't handled by browsers or isn't even covered by the RFC.
This is the reason why SessionAuth doesn't return 401. It just doesn't make sense because the client can not send a session id on its own.

I agree a 401 would be better but it's technically incorrect with session auth.
And I recon that the proposed change, although making things easier won't make them simpler. Would lead to wierd side effect with settings such as:

```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    )
}
```

**Comment by kevin-brown** [comment]
This issue has come up before, there's a pretty lengthy discussion in https://github.com/tomchristie/django-rest-framework/pull/1611 that I'll defer to for now.

**Comment by leonardoarroyo** [comment]
Sounds right, I didn't find this issue before. I'm closing this one.

**Comment by Aniket-Singla** [comment]
Hi @xordoquy , I know I am pretty late to comment on the issue. But what is the point of returning the header based on first authenticator present in settings ( return authenticators[0].authenticate_header(request) )?

In case I support both session and basic authentication, it will always returns 403 for AuthenticationFailed / NotAuthenticated exceptions if i keep SessionAuthentication at first place in settings. I believe expected behaviour should be to return headers based on the type of authentication being used for the request.
