### ISSUE TITLE
UniqueTogetherValidator should include existing entity as named argument in format

### ISSUE THREAD

**Issue by jacobg** [tomchristie/django-rest-framework#4686]
It'd be great to do something like this:
`raise ValidationError(message.format(field_names=field_names, entity=queryset[0]))
`so that the message string can do something like this:
`message='Employee "{entity.first_name} {entity.last_name}" already uses this employee id. Each employee id must be unique.'`

**Comment by tomchristie** [comment]
Thanks for the suggestion! I'd be perfectly happy to *consider* work in this direction if someone chose to take it on. (That certainly doesn't mean it'd be accepted, but we could consider it on it's merits) However I'm not particularly minded to prioritize it otherwise. Perhaps if it gets re-raised independently at a later date we could reconsider.
