### ISSUE TITLE
Specify that auth token is symmetric

### ISSUE THREAD

**Issue by XeniaGabriela** [tomchristie/django-rest-framework#4700]
The auth token is a basic symmetric version of a token, which is a string of 20 random bytes suitable for cryptographic use.

There is also an asymmetric RSA-based version of token handling.

It would be nice to specify this in the documentation, because it has an impact on security. An asymmetric version would be more secure because the users/clients token is not the same as the matching token on the server side.

So far the version of the token is not specified.

**Comment by tomchristie** [comment]
Thanks for raising this. Any pointers towards how we'd implement an asymmetric exquivelent of the basic token auth? Want to outline in plainer language the implications of the tokens differing on client and server side?

**Comment by xordoquy** [comment]
I'm not sure adding asymmetric is the way we want to go as we've always rejected improvement to keep it basic.
However, we indeed should warn about this in the doc and point to some more advanced alternative

**Comment by tomchristie** [comment]
> we indeed should warn about this in the doc

Sure, tho I would like to see a plainer description. "would be more secure because the users/clients token is not the same as the matching token on the server side." isn't a complete.

Also:

* We might want to be more general about this - there's plenty of reasons to use something other than the fairly ad-hoc token authentication.
* If we *really* want to tackle this the right approach is probably to actually promote JWT as the default, and start to sideline the existing TokenAuthentication one way or another.

**Comment by tomchristie** [comment]
Concrete PRs towards the docs could be considered on their own merits. Unconvinced that referencing "symmetric" is going to be particularly beneficial for users. More likely that we could re-consider what auth implementations we ought to steer users towards by default.
