### ISSUE TITLE
Subparsers for MultiPartParser

### ISSUE THREAD

**Issue by TZanke** [tomchristie/django-rest-framework#4881]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Post a `multipart/form-data` content-type request to a DRF `MultiPartParser` view.
One of the multiparts contains the content_type text/json
```

Content-Type: multipart/form-data;boundary=------FormBoundary15a13bb0cf2
Content-Length: xyz

------FormBoundary15a13bb0cf2
Content-Disposition: form-data; name="json"
Content-Type: text/json

{   "x": "3" }
------FormBoundary15a13bb0cf2--


```
## Expected behavior

`request.data['json']` as json dict

## Actual behavior
`request.data['json']` is a unicode string

multipart entrys are not parsed with any DRF Parser.
At the moment i manually parse the JSON part, but i think the parts should be automatically parsed by DRF to support Clients `Content-Type` header.

**Comment by xordoquy** [comment]
From the [documentation](http://www.django-rest-framework.org/api-guide/parsers/#multipartparser):

> Parses multipart HTML form content, which supports file uploads.

Which excludes the JSON content type here.
I'm closing this issue as it's not expected that JSON content type will be parsed.

As for the support of the JSON content type in the multipart, I'll have to get a better understanding of the multipart before taking a decision.

**Comment by TZanke** [comment]
We need a creating API for a Model plus associated files. Because we need both in a atomic API call, we decided to use a multipart. See [1] and [2] it looks possible with multipart.

[1] https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html
[2] https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2

**Comment by xordoquy** [comment]
@TZanke I like the idea in itself. Thought about that myself some time ago.
Maybe @tomchristie will also give its feedback about that.

**Comment by tomchristie** [comment]
Yup after looking around I can't see anything that discounts this as an option.
Is it something that we'd want to put on the backlog for addressing in core? Probably not particularly at the moment - I think you'd have a hard time finding many clients that'd easily support that usage. That doesn't mean that we couldn't consider pull requests that refactored things to allow it to be possible, but I don't see it being sufficiently important to prioritize unless someone wants to proactively take a look at addressing it (and even then it's not a given that it'd get in - would still need to pass the "how much benefit vs. how much extra complexity" test)

Resolution for now:

Either address this in a third party package, demonstrating how we'd do it in core, *or* take it on as a pull request that we can assess on it's own merits.

**Comment by mpeuss** [comment]
Here is an example of an API using `application/json` content type with `multipart/form-data`:
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_insert_update_blob.htm

Nonetheless, may it be an issue of Django  instead of DRF? For non `multipart/form-data` requests the content type is correctly applied to the POST data.

**Comment by xordoquy** [comment]
The very beginning here is to write down a simple test case that showcase a multipart with mixed content types. That will help understanding who should do what and provide a starting point for any further change.

**Comment by tomchristie** [comment]
> Here is an example of an API using application/json content type with multipart/form-data

Indeed - it's also pretty awkward (note that they're having to explicitly construct the multipart body there rather than curl being able to handle it automatically)

Notionally this is something that could go in, but unless JSON in multipart becomes more commonly supported it's not something I think we should spend too much effort considering.

**Comment by timliim** [comment]
These 3 issues are related.
[1] https://code.djangoproject.com/ticket/21442
[2] https://code.djangoproject.com/ticket/28678
[3] https://github.com/encode/django-rest-framework/issues/4881

[1] is the overall tracker for this issue, desires to create a configurable parser.  Opened 9 years ago.
[3] describes the desired behavior with example.  Opened 5 years ago.
[2] has a proposed fix (credit: Facundo Batista).  The fix is simple and worked well when I tried it.  Opened 5 years ago.

Surely a configurable parser [1] is a good goal to pursue.  But if it
takes 9 years before anything happens, perhaps we can take [2]?  It is
not configurable, but it works well.

re: a case for multipart parser that can handle json parts
I have an api that takes some json input, plus 2 optional image files.
With json parser, I cannot easily include image files (base64 works, but
clumsy for modest size images).
Multipart parser allows me to send the json input plus images in 1
call.  But all the data parts are treated as text (str).  One of the
data field is a dict (eg. { "x": 7, "y": 5 }).
If I use json parser, it is an dict (good).
If I use multipart parser, it becomes a str (bad; desired to get a
dict).

**Comment by tomchristie** [comment]
I don't think we need to take this responsibility on within the core repo.

Parsers are configurable, so the right place for any work to start here (if there's sufficient motivation) is as a third party package that provides an alternative MultiPartParser implementation.
