### ISSUE TITLE
Serializer failed to look attributes of reverse Foreign Key

### ISSUE THREAD

**Issue by childeoapp** [tomchristie/django-rest-framework#4929]
## Steps to reproduce
Considering the following models:
```
class Farm(models.Model):
    name = models.CharField(max_length=200)

class Animal(models.Model):
    name = models.CharField(max_length=200)

class AnimalFarm(models.Model):
    farm = models.ForeignKey(Farm, related_name='farm_animal')
    animal = models.ForeignKey(Animal, related_name='farm_animal')

    class Meta:
        unique_together = ('farm', 'animal')
```
_Here, we cannot use a 'through' ManyToMany relationship because **Farm** and **Animal** are part of 2 different apps that we cannot modify. We can only work on **AnimalFarm**._

For the serializer we make:
```
class FarmSerializer(serializers.HyperlinkedModelSerializer):
    animals = serializers.HyperlinkedRelatedField(
        many=True,
        read_only=True,
        view_name='animal-detail',
        source='farm_animal.animal'
    )

    class Meta:
        model = Farm
        fields = ('name', 'animals')
```

## Expected behavior
We expect that the _animals_ fields become an array that contains the URL of all **Animals** that are related with the current **Farm**

## Actual behavior
This create an **AttributeError 'RelatedManager' object has no attribute 'animal'**
When working with a "normal" ForeignKey the "." notation doesn't create this error, neither if I use a 'through' ManyToMany relationship.
PS: if the source is just 'farm_animal' it's get the good id

**Comment by carltongibson** [comment]
As it stands this is expected behaviour. 

`source='farm_animal.animal` doesn't make sense. `farm_animal` here is an iterable of the `AnimalFarm` farm instances that are at the other end of the One-to-Many Foreign Key relationship from `AnimalFarm` to `Farm`.

Each item in that iterable will have the `animal` attribute but the iterable as a whole does not. (If you didn't provide the `related_name` parameter it would be called `farm_set`, which gives you the clue.)

You're going to need to do something different to get the result you want. You could subclass `HyperlinkedRelatedField` to return the `url` of the related `animal` in `to_representation`, **if you just need a read-only field**. Otherwise think about a nested serialiser.
