### ISSUE TITLE
Authentication Check Not Progressing with same Keyword in Auth Header

### ISSUE THREAD

**Issue by bd60** [tomchristie/django-rest-framework#5023]
## Steps to reproduce
I have subclassed Token Auth as recommended to use the keyword "Bearer".

I also use facebook authentication which uses the same keyword "Bearer" (through djang-rest-framework-social-auth).

Both are listed in default Auth Classes, however, only the first listed class is checked.  

## Expected behavior

I would expect the auth progression to continue checking no matter what they keyword is. 

## Actual behavior

Progression stops at first auth class using that keyword.  When using different keywords (such as Token and Bearer), it completes all checks.

**Comment by tomchristie** [comment]
If an authentication class returns `None` then the authentication checks *will* continue.
Most likely both of your implementations are raising an `AuthenticationFailed` error.
If you change the implementation so that they *don't* fail, but simply return `None`, then you'll be able to use both together. (The problem tho is that you won't be able to differentiate between a user who supplies invalid credentials and a request that does not include any credentials)
